/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { actionGuildJoinRequest } from "../../funcs/actionGuildJoinRequest.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ActionGuildJoinRequestRequest$inboundSchema,
};

export const tool$actionGuildJoinRequest: ToolDefinition<typeof args> = {
  name: "action-guild-join-request",
  description: `Approve or reject guild join request`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await actionGuildJoinRequest(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
