/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicationRoleConnectionMetadataUpdate } from "../../funcs/applicationRoleConnectionMetadataUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.UpdateApplicationRoleConnectionsMetadataRequest$inboundSchema,
};

export const tool$applicationRoleConnectionMetadataUpdate: ToolDefinition<
  typeof args
> = {
  name: "application-role-connection-metadata-update",
  description:
    `Updates and returns a list of application role connection metadata objects for the given application. An application can have a maximum of 5 metadata records.`,
  scopes: ["application-role-connection-metadata", "write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await applicationRoleConnectionMetadataUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
