/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicationsPartnerSDKUnmergeProvisionalAccount } from "../../funcs/applicationsPartnerSDKUnmergeProvisionalAccount.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.PartnerSDKUnmergeProvisionalAccountRequestBody$inboundSchema,
};

export const tool$applicationsPartnerSDKUnmergeProvisionalAccount:
  ToolDefinition<typeof args> = {
    name: "applications-partner-SDK-unmerge-provisional-account",
    description: `Unmerges a provisional account.`,
    scopes: ["application", "write"],
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await applicationsPartnerSDKUnmergeProvisionalAccount(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
