/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { botPartnerSDKUnmergeProvisionalAccount } from "../../funcs/botPartnerSDKUnmergeProvisionalAccount.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.BotPartnerSDKUnmergeProvisionalAccountRequestBody$inboundSchema,
};

export const tool$botPartnerSDKUnmergeProvisionalAccount: ToolDefinition<
  typeof args
> = {
  name: "bot-partner-SDK-unmerge-provisional-account",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await botPartnerSDKUnmergeProvisionalAccount(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
