/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { channelsJoinThread } from "../../funcs/channelsJoinThread.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.JoinThreadRequest$inboundSchema,
};

export const tool$channelsJoinThread: ToolDefinition<typeof args> = {
  name: "channels-join-thread",
  description:
    `Adds the current user to a thread. Also requires the thread is not archived. Returns a 204 empty response on success. Fires a Thread Members Update and a Thread Create Gateway event.`,
  scopes: ["channels", "write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await channelsJoinThread(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
