/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { createInteractionResponse } from "../../funcs/createInteractionResponse.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateInteractionResponseRequest$inboundSchema,
};

export const tool$createInteractionResponse: ToolDefinition<typeof args> = {
  name: "create-interaction-response",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await createInteractionResponse(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value?.result;

    return formatResult(value, apiCall);
  },
};
