/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deleteGuildScheduledEventException } from "../../funcs/deleteGuildScheduledEventException.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteGuildScheduledEventExceptionRequest$inboundSchema,
};

export const tool$deleteGuildScheduledEventException: ToolDefinition<
  typeof args
> = {
  name: "delete-guild-scheduled-event-exception",
  description: `Delete an exception to a recurring guild scheduled event`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await deleteGuildScheduledEventException(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
