/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { editLobby } from "../../funcs/editLobby.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.EditLobbyRequest$inboundSchema,
};

export const tool$editLobby: ToolDefinition<typeof args> = {
  name: "edit-lobby",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await editLobby(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
