/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { emojiCreateApplicationEmoji } from "../../funcs/emojiCreateApplicationEmoji.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateApplicationEmojiRequest$inboundSchema,
};

export const tool$emojiCreateApplicationEmoji: ToolDefinition<typeof args> = {
  name: "emoji-create-application-emoji",
  description:
    `Create a new emoji for the application. Returns the new emoji object on success.`,
  scopes: ["emoji", "write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await emojiCreateApplicationEmoji(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
