/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getCurrentUserApplicationEntitlements } from "../../funcs/getCurrentUserApplicationEntitlements.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.GetCurrentUserApplicationEntitlementsRequest$inboundSchema,
};

export const tool$getCurrentUserApplicationEntitlements: ToolDefinition<
  typeof args
> = {
  name: "get-current-user-application-entitlements",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getCurrentUserApplicationEntitlements(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
