/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { guildSearch } from "../../funcs/guildSearch.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GuildSearchRequest$inboundSchema,
};

export const tool$guildSearch: ToolDefinition<typeof args> = {
  name: "guild-search",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await guildSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
