/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { guildTemplatesList } from "../../funcs/guildTemplatesList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListGuildTemplatesRequest$inboundSchema,
};

export const tool$guildTemplatesList: ToolDefinition<typeof args> = {
  name: "guild-templates-list",
  description:
    `Returns an array of guild template objects. Requires the MANAGE_GUILD permission.`,
  scopes: ["guild-template", "read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await guildTemplatesList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
