/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { guildScheduledEventsCreate } from "../../funcs/guildScheduledEventsCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateGuildScheduledEventRequest$inboundSchema,
};

export const tool$guildScheduledEventsCreate: ToolDefinition<typeof args> = {
  name: "guild-scheduled-events-create",
  description:
    `Create a guild scheduled event in the guild. Returns a guild scheduled event object on success. Fires a Guild Scheduled Event Create Gateway event.`,
  scopes: ["guild-scheduled-event", "write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await guildScheduledEventsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
