/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { listGuildScheduledEventExceptionUsers } from "../../funcs/listGuildScheduledEventExceptionUsers.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.ListGuildScheduledEventExceptionUsersRequest$inboundSchema,
};

export const tool$listGuildScheduledEventExceptionUsers: ToolDefinition<
  typeof args
> = {
  name: "list-guild-scheduled-event-exception-users",
  description:
    `Get a list of users subscribed to a guild scheduled event exception`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await listGuildScheduledEventExceptionUsers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
