/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesDeleteAllReactionsForEmoji } from "../../funcs/messagesDeleteAllReactionsForEmoji.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteAllMessageReactionsByEmojiRequest$inboundSchema,
};

export const tool$messagesDeleteAllReactionsForEmoji: ToolDefinition<
  typeof args
> = {
  name: "messages-delete-all-reactions-for-emoji",
  description:
    `Deletes all the reactions for a given emoji on a message. This endpoint requires the MANAGE_MESSAGES permission to be present on the current user.`,
  scopes: ["messages", "write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesDeleteAllReactionsForEmoji(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
