/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesCreateReaction } from "../../funcs/messagesCreateReaction.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.AddMyMessageReactionRequest$inboundSchema,
};

export const tool$messagesCreateReaction: ToolDefinition<typeof args> = {
  name: "messages-create-reaction",
  description:
    `Create a reaction for the message. This endpoint requires the READ_MESSAGE_HISTORY permission to be present on the current user.`,
  scopes: ["messages", "write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesCreateReaction(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
