/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { stickersListPacks } from "../../funcs/stickersListPacks.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$stickersListPacks: ToolDefinition = {
  name: "stickers-list-packs",
  description: `Returns a list of available sticker packs.`,
  scopes: ["stickers", "read"],
  tool: async (client, ctx) => {
    const [result, apiCall] = await stickersListPacks(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
