/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersUpdateApplicationRoleConnection } from "../../funcs/usersUpdateApplicationRoleConnection.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateApplicationUserRoleConnectionRequest$inboundSchema,
};

export const tool$usersUpdateApplicationRoleConnection: ToolDefinition<
  typeof args
> = {
  name: "users-update-application-role-connection",
  description:
    `Updates and returns the application role connection for the user. Requires an OAuth2 access token with role_connections.write scope for the application specified in the path.`,
  scopes: ["users", "write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersUpdateApplicationRoleConnection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
