/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceGetUserState } from "../../funcs/voiceGetUserState.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetVoiceStateRequest$inboundSchema,
};

export const tool$voiceGetUserState: ToolDefinition<typeof args> = {
  name: "voice-get-user-state",
  description: `Returns the specified user's voice state in the guild.`,
  scopes: ["voice", "read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await voiceGetUserState(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
