/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export const mcpScopes = [
  "application",
  "application-role-connection-metadata",
  "audit-logs",
  "auto-moderation",
  "channels",
  "emoji",
  "entitlements",
  "guild-scheduled-event",
  "guild-template",
  "guilds",
  "invites",
  "lobby",
  "messages",
  "polls",
  "read",
  "soundboard",
  "stage-instance",
  "stickers",
  "users",
  "voice",
  "webhooks",
  "write",
] as const;

export type MCPScope = (typeof mcpScopes)[number];
