/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicationCommandsBulkSet } from "../funcs/applicationCommandsBulkSet.js";
import { applicationCommandsCreateForGuild } from "../funcs/applicationCommandsCreateForGuild.js";
import { applicationCommandsDelete } from "../funcs/applicationCommandsDelete.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ApplicationCommands extends ClientSDK {
  async createForGuild(
    security: operations.CreateGuildApplicationCommandSecurity,
    request: operations.CreateGuildApplicationCommandRequest,
    options?: RequestOptions,
  ): Promise<components.ApplicationCommandResponse> {
    return unwrapAsync(applicationCommandsCreateForGuild(
      this,
      security,
      request,
      options,
    ));
  }

  async delete(
    security: operations.DeleteApplicationCommandSecurity,
    request: operations.DeleteApplicationCommandRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(applicationCommandsDelete(
      this,
      security,
      request,
      options,
    ));
  }

  async bulkSet(
    security: operations.BulkSetApplicationCommandsSecurity,
    request: operations.BulkSetApplicationCommandsRequest,
    options?: RequestOptions,
  ): Promise<Array<components.ApplicationCommandResponse>> {
    return unwrapAsync(applicationCommandsBulkSet(
      this,
      security,
      request,
      options,
    ));
  }
}
