/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { guildsApplicationCommandPermissionsList } from "../funcs/guildsApplicationCommandPermissionsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ApplicationCommandPermissions extends ClientSDK {
  async list(
    security: operations.ListGuildApplicationCommandPermissionsSecurity,
    request: operations.ListGuildApplicationCommandPermissionsRequest,
    options?: RequestOptions,
  ): Promise<Array<components.CommandPermissionsResponse>> {
    return unwrapAsync(guildsApplicationCommandPermissionsList(
      this,
      security,
      request,
      options,
    ));
  }
}
