/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditLogsList } from "../funcs/auditLogsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AuditLogs extends ClientSDK {
  /**
   * Returns an audit log object for the guild. Requires the VIEW_AUDIT_LOG permission.
   */
  async list(
    request: operations.ListGuildAuditLogEntriesRequest,
    options?: RequestOptions,
  ): Promise<components.GuildAuditLogResponse> {
    return unwrapAsync(auditLogsList(
      this,
      request,
      options,
    ));
  }
}
