/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dmCreate } from "../funcs/dmCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Dm extends ClientSDK {
  async create(
    request: components.CreatePrivateChannelRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateDmResponseBody> {
    return unwrapAsync(dmCreate(
      this,
      request,
      options,
    ));
  }
}
