/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { guildStickersCreate } from "../funcs/guildStickersCreate.js";
import { guildStickersGet } from "../funcs/guildStickersGet.js";
import { guildStickersUpdate } from "../funcs/guildStickersUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class GuildStickers extends ClientSDK {
  async get(
    request: operations.GetGuildStickerRequest,
    options?: RequestOptions,
  ): Promise<components.GuildStickerResponse> {
    return unwrapAsync(guildStickersGet(
      this,
      request,
      options,
    ));
  }

  async create(
    request: operations.CreateGuildStickerRequest,
    options?: RequestOptions,
  ): Promise<components.GuildStickerResponse> {
    return unwrapAsync(guildStickersCreate(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.UpdateGuildStickerRequest,
    options?: RequestOptions,
  ): Promise<components.GuildStickerResponse> {
    return unwrapAsync(guildStickersUpdate(
      this,
      request,
      options,
    ));
  }
}
