/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { guildsAddMemberRole } from "../funcs/guildsAddMemberRole.js";
import { guildsBanUser } from "../funcs/guildsBanUser.js";
import { guildsBulkBanUsers } from "../funcs/guildsBulkBanUsers.js";
import { guildsBulkUpdateRoles } from "../funcs/guildsBulkUpdateRoles.js";
import { guildsCreate } from "../funcs/guildsCreate.js";
import { guildsCreateEmoji } from "../funcs/guildsCreateEmoji.js";
import { guildsCreateRole } from "../funcs/guildsCreateRole.js";
import { guildsCreateScheduledEvent } from "../funcs/guildsCreateScheduledEvent.js";
import { guildsCreateSoundboardSound } from "../funcs/guildsCreateSoundboardSound.js";
import { guildsCreateTemplate } from "../funcs/guildsCreateTemplate.js";
import { guildsDelete } from "../funcs/guildsDelete.js";
import { guildsDeleteAutoModerationRule } from "../funcs/guildsDeleteAutoModerationRule.js";
import { guildsDeleteMemberRole } from "../funcs/guildsDeleteMemberRole.js";
import { guildsDeleteRole } from "../funcs/guildsDeleteRole.js";
import { guildsDeleteScheduledEvent } from "../funcs/guildsDeleteScheduledEvent.js";
import { guildsDeleteSoundboardSound } from "../funcs/guildsDeleteSoundboardSound.js";
import { guildsDeleteSticker } from "../funcs/guildsDeleteSticker.js";
import { guildsGet } from "../funcs/guildsGet.js";
import { guildsGetAuditLogEntries } from "../funcs/guildsGetAuditLogEntries.js";
import { guildsGetAutoModerationRule } from "../funcs/guildsGetAutoModerationRule.js";
import { guildsGetNewMemberWelcome } from "../funcs/guildsGetNewMemberWelcome.js";
import { guildsGetOnboarding } from "../funcs/guildsGetOnboarding.js";
import { guildsGetPreview } from "../funcs/guildsGetPreview.js";
import { guildsGetRole } from "../funcs/guildsGetRole.js";
import { guildsGetRoles } from "../funcs/guildsGetRoles.js";
import { guildsGetVanityUrl } from "../funcs/guildsGetVanityUrl.js";
import { guildsGetWelcomeScreen } from "../funcs/guildsGetWelcomeScreen.js";
import { guildsGetWidget } from "../funcs/guildsGetWidget.js";
import { guildsGetWidgetPng } from "../funcs/guildsGetWidgetPng.js";
import { guildsGetWidgetSettings } from "../funcs/guildsGetWidgetSettings.js";
import { guildsListBans } from "../funcs/guildsListBans.js";
import { guildsListChannels } from "../funcs/guildsListChannels.js";
import { guildsListMembers } from "../funcs/guildsListMembers.js";
import { guildsListSoundboardSounds } from "../funcs/guildsListSoundboardSounds.js";
import { guildsListStickers } from "../funcs/guildsListStickers.js";
import { guildsListTemplates } from "../funcs/guildsListTemplates.js";
import { guildsListWebhooks } from "../funcs/guildsListWebhooks.js";
import { guildsPrune } from "../funcs/guildsPrune.js";
import { guildsSearchMembers } from "../funcs/guildsSearchMembers.js";
import { guildsSetMfaLevel } from "../funcs/guildsSetMfaLevel.js";
import { guildsUnbanUser } from "../funcs/guildsUnbanUser.js";
import { guildsUpdate } from "../funcs/guildsUpdate.js";
import { guildsUpdateAutoModerationRule } from "../funcs/guildsUpdateAutoModerationRule.js";
import { guildsUpdateChannels } from "../funcs/guildsUpdateChannels.js";
import { guildsUpdateEmoji } from "../funcs/guildsUpdateEmoji.js";
import { guildsUpdateMember } from "../funcs/guildsUpdateMember.js";
import { guildsUpdateMyMember } from "../funcs/guildsUpdateMyMember.js";
import { guildsUpdateOnboarding } from "../funcs/guildsUpdateOnboarding.js";
import { guildsUpdateSelfVoiceState } from "../funcs/guildsUpdateSelfVoiceState.js";
import { guildsUpdateWelcomeScreen } from "../funcs/guildsUpdateWelcomeScreen.js";
import { guildsUpdateWidgetSettings } from "../funcs/guildsUpdateWidgetSettings.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { ApplicationCommandPermissions } from "./applicationcommandpermissions.js";
import { DiscordApplicationCommands } from "./discordapplicationcommands.js";
import { DiscordAutoModerationRules } from "./discordautomoderationrules.js";
import { DiscordEmojis } from "./discordemojis.js";
import { Integrations } from "./integrations.js";
import { Members } from "./members.js";
import { Regions } from "./regions.js";
import { Roles } from "./roles.js";
import { ScheduledEvents } from "./scheduledevents.js";
import { Templates } from "./templates.js";

export class Guilds extends ClientSDK {
  private _applicationCommandPermissions?: ApplicationCommandPermissions;
  get applicationCommandPermissions(): ApplicationCommandPermissions {
    return (this._applicationCommandPermissions ??=
      new ApplicationCommandPermissions(this._options));
  }

  private _applicationCommands?: DiscordApplicationCommands;
  get applicationCommands(): DiscordApplicationCommands {
    return (this._applicationCommands ??= new DiscordApplicationCommands(
      this._options,
    ));
  }

  private _autoModerationRules?: DiscordAutoModerationRules;
  get autoModerationRules(): DiscordAutoModerationRules {
    return (this._autoModerationRules ??= new DiscordAutoModerationRules(
      this._options,
    ));
  }

  private _templates?: Templates;
  get templates(): Templates {
    return (this._templates ??= new Templates(this._options));
  }

  private _scheduledEvents?: ScheduledEvents;
  get scheduledEvents(): ScheduledEvents {
    return (this._scheduledEvents ??= new ScheduledEvents(this._options));
  }

  private _integrations?: Integrations;
  get integrations(): Integrations {
    return (this._integrations ??= new Integrations(this._options));
  }

  private _members?: Members;
  get members(): Members {
    return (this._members ??= new Members(this._options));
  }

  private _regions?: Regions;
  get regions(): Regions {
    return (this._regions ??= new Regions(this._options));
  }

  private _emojis?: DiscordEmojis;
  get emojis(): DiscordEmojis {
    return (this._emojis ??= new DiscordEmojis(this._options));
  }

  private _roles?: Roles;
  get roles(): Roles {
    return (this._roles ??= new Roles(this._options));
  }

  async create(
    request: components.GuildCreateRequest,
    options?: RequestOptions,
  ): Promise<components.GuildResponse> {
    return unwrapAsync(guildsCreate(
      this,
      request,
      options,
    ));
  }

  async getAutoModerationRule(
    request: operations.GetAutoModerationRuleRequest,
    options?: RequestOptions,
  ): Promise<operations.GetAutoModerationRuleResponseBody> {
    return unwrapAsync(guildsGetAutoModerationRule(
      this,
      request,
      options,
    ));
  }

  async deleteAutoModerationRule(
    request: operations.DeleteAutoModerationRuleRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(guildsDeleteAutoModerationRule(
      this,
      request,
      options,
    ));
  }

  async updateAutoModerationRule(
    request: operations.UpdateAutoModerationRuleRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateAutoModerationRuleResponseBody> {
    return unwrapAsync(guildsUpdateAutoModerationRule(
      this,
      request,
      options,
    ));
  }

  async updateSelfVoiceState(
    request: operations.UpdateSelfVoiceStateRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(guildsUpdateSelfVoiceState(
      this,
      request,
      options,
    ));
  }

  async searchMembers(
    request: operations.SearchGuildMembersRequest,
    options?: RequestOptions,
  ): Promise<Array<components.GuildMemberResponse>> {
    return unwrapAsync(guildsSearchMembers(
      this,
      request,
      options,
    ));
  }

  async updateMyMember(
    request: operations.UpdateMyGuildMemberRequest,
    options?: RequestOptions,
  ): Promise<components.PrivateGuildMemberResponse> {
    return unwrapAsync(guildsUpdateMyMember(
      this,
      request,
      options,
    ));
  }

  async addMemberRole(
    request: operations.AddGuildMemberRoleRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(guildsAddMemberRole(
      this,
      request,
      options,
    ));
  }

  async deleteMemberRole(
    request: operations.DeleteGuildMemberRoleRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(guildsDeleteMemberRole(
      this,
      request,
      options,
    ));
  }

  async getNewMemberWelcome(
    request: operations.GetGuildNewMemberWelcomeRequest,
    options?: RequestOptions,
  ): Promise<components.GuildHomeSettingsResponse | undefined> {
    return unwrapAsync(guildsGetNewMemberWelcome(
      this,
      request,
      options,
    ));
  }

  async deleteSoundboardSound(
    request: operations.DeleteGuildSoundboardSoundRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(guildsDeleteSoundboardSound(
      this,
      request,
      options,
    ));
  }

  async listSoundboardSounds(
    request: operations.ListGuildSoundboardSoundsRequest,
    options?: RequestOptions,
  ): Promise<components.ListGuildSoundboardSoundsResponse> {
    return unwrapAsync(guildsListSoundboardSounds(
      this,
      request,
      options,
    ));
  }

  async createSoundboardSound(
    request: operations.CreateGuildSoundboardSoundRequest,
    options?: RequestOptions,
  ): Promise<components.SoundboardSoundResponse> {
    return unwrapAsync(guildsCreateSoundboardSound(
      this,
      request,
      options,
    ));
  }

  async deleteScheduledEvent(
    request: operations.DeleteGuildScheduledEventRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(guildsDeleteScheduledEvent(
      this,
      request,
      options,
    ));
  }

  async createScheduledEvent(
    request: operations.CreateGuildScheduledEventRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateGuildScheduledEventResponseBody> {
    return unwrapAsync(guildsCreateScheduledEvent(
      this,
      request,
      options,
    ));
  }

  async getWelcomeScreen(
    request: operations.GetGuildWelcomeScreenRequest,
    options?: RequestOptions,
  ): Promise<components.GuildWelcomeScreenResponse> {
    return unwrapAsync(guildsGetWelcomeScreen(
      this,
      request,
      options,
    ));
  }

  async updateWelcomeScreen(
    request: operations.UpdateGuildWelcomeScreenRequest,
    options?: RequestOptions,
  ): Promise<components.GuildWelcomeScreenResponse> {
    return unwrapAsync(guildsUpdateWelcomeScreen(
      this,
      request,
      options,
    ));
  }

  async getWidget(
    request: operations.GetGuildWidgetRequest,
    security?: operations.GetGuildWidgetSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.WidgetResponse> {
    return unwrapAsync(guildsGetWidget(
      this,
      request,
      security,
      options,
    ));
  }

  async getOnboarding(
    request: operations.GetGuildsOnboardingRequest,
    options?: RequestOptions,
  ): Promise<components.UserGuildOnboardingResponse> {
    return unwrapAsync(guildsGetOnboarding(
      this,
      request,
      options,
    ));
  }

  async updateOnboarding(
    request: operations.PutGuildsOnboardingRequest,
    options?: RequestOptions,
  ): Promise<components.GuildOnboardingResponse> {
    return unwrapAsync(guildsUpdateOnboarding(
      this,
      request,
      options,
    ));
  }

  async getVanityUrl(
    request: operations.GetGuildVanityUrlRequest,
    options?: RequestOptions,
  ): Promise<components.VanityURLResponse> {
    return unwrapAsync(guildsGetVanityUrl(
      this,
      request,
      options,
    ));
  }

  async getAuditLogEntries(
    request: operations.ListGuildAuditLogEntriesRequest,
    options?: RequestOptions,
  ): Promise<components.GuildAuditLogResponse> {
    return unwrapAsync(guildsGetAuditLogEntries(
      this,
      request,
      options,
    ));
  }

  async getWidgetPng(
    request: operations.GetGuildWidgetPngRequest,
    security?: operations.GetGuildWidgetPngSecurity | undefined,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(guildsGetWidgetPng(
      this,
      request,
      security,
      options,
    ));
  }

  async listTemplates(
    request: operations.ListGuildTemplatesRequest,
    options?: RequestOptions,
  ): Promise<Array<components.GuildTemplateResponse>> {
    return unwrapAsync(guildsListTemplates(
      this,
      request,
      options,
    ));
  }

  async createTemplate(
    request: operations.CreateGuildTemplateRequest,
    options?: RequestOptions,
  ): Promise<components.GuildTemplateResponse> {
    return unwrapAsync(guildsCreateTemplate(
      this,
      request,
      options,
    ));
  }

  async deleteSticker(
    request: operations.DeleteGuildStickerRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(guildsDeleteSticker(
      this,
      request,
      options,
    ));
  }

  async bulkBanUsers(
    request: operations.BulkBanUsersFromGuildRequest,
    options?: RequestOptions,
  ): Promise<components.BulkBanUsersResponse> {
    return unwrapAsync(guildsBulkBanUsers(
      this,
      request,
      options,
    ));
  }

  async listStickers(
    request: operations.ListGuildStickersRequest,
    options?: RequestOptions,
  ): Promise<Array<components.GuildStickerResponse>> {
    return unwrapAsync(guildsListStickers(
      this,
      request,
      options,
    ));
  }

  async listWebhooks(
    request: operations.GetGuildWebhooksRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.GetGuildWebhooksResponseBody>> {
    return unwrapAsync(guildsListWebhooks(
      this,
      request,
      options,
    ));
  }

  async listChannels(
    security: operations.ListGuildChannelsSecurity,
    request: operations.ListGuildChannelsRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.ListGuildChannelsResponseBody>> {
    return unwrapAsync(guildsListChannels(
      this,
      security,
      request,
      options,
    ));
  }

  async updateChannels(
    request: operations.BulkUpdateGuildChannelsRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(guildsUpdateChannels(
      this,
      request,
      options,
    ));
  }

  async updateMember(
    request: operations.UpdateGuildMemberRequest,
    options?: RequestOptions,
  ): Promise<components.GuildMemberResponse | undefined> {
    return unwrapAsync(guildsUpdateMember(
      this,
      request,
      options,
    ));
  }

  async listMembers(
    request: operations.ListGuildMembersRequest,
    options?: RequestOptions,
  ): Promise<Array<components.GuildMemberResponse>> {
    return unwrapAsync(guildsListMembers(
      this,
      request,
      options,
    ));
  }

  async getPreview(
    request: operations.GetGuildPreviewRequest,
    options?: RequestOptions,
  ): Promise<components.GuildPreviewResponse> {
    return unwrapAsync(guildsGetPreview(
      this,
      request,
      options,
    ));
  }

  async updateEmoji(
    request: operations.UpdateGuildEmojiRequest,
    options?: RequestOptions,
  ): Promise<components.EmojiResponse> {
    return unwrapAsync(guildsUpdateEmoji(
      this,
      request,
      options,
    ));
  }

  async createEmoji(
    request: operations.CreateGuildEmojiRequest,
    options?: RequestOptions,
  ): Promise<components.EmojiResponse> {
    return unwrapAsync(guildsCreateEmoji(
      this,
      request,
      options,
    ));
  }

  async getWidgetSettings(
    request: operations.GetGuildWidgetSettingsRequest,
    options?: RequestOptions,
  ): Promise<components.WidgetSettingsResponse> {
    return unwrapAsync(guildsGetWidgetSettings(
      this,
      request,
      options,
    ));
  }

  async updateWidgetSettings(
    request: operations.UpdateGuildWidgetSettingsRequest,
    options?: RequestOptions,
  ): Promise<components.WidgetSettingsResponse> {
    return unwrapAsync(guildsUpdateWidgetSettings(
      this,
      request,
      options,
    ));
  }

  async getRole(
    request: operations.GetGuildRoleRequest,
    options?: RequestOptions,
  ): Promise<components.GuildRoleResponse> {
    return unwrapAsync(guildsGetRole(
      this,
      request,
      options,
    ));
  }

  async deleteRole(
    request: operations.DeleteGuildRoleRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(guildsDeleteRole(
      this,
      request,
      options,
    ));
  }

  async getRoles(
    request: operations.ListGuildRolesRequest,
    options?: RequestOptions,
  ): Promise<Array<components.GuildRoleResponse>> {
    return unwrapAsync(guildsGetRoles(
      this,
      request,
      options,
    ));
  }

  async createRole(
    request: operations.CreateGuildRoleRequest,
    options?: RequestOptions,
  ): Promise<components.GuildRoleResponse> {
    return unwrapAsync(guildsCreateRole(
      this,
      request,
      options,
    ));
  }

  async bulkUpdateRoles(
    request: operations.BulkUpdateGuildRolesRequest,
    options?: RequestOptions,
  ): Promise<Array<components.GuildRoleResponse>> {
    return unwrapAsync(guildsBulkUpdateRoles(
      this,
      request,
      options,
    ));
  }

  async prune(
    request: operations.PruneGuildRequest,
    options?: RequestOptions,
  ): Promise<components.GuildPruneResponse> {
    return unwrapAsync(guildsPrune(
      this,
      request,
      options,
    ));
  }

  async banUser(
    request: operations.BanUserFromGuildRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(guildsBanUser(
      this,
      request,
      options,
    ));
  }

  async unbanUser(
    request: operations.UnbanUserFromGuildRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(guildsUnbanUser(
      this,
      request,
      options,
    ));
  }

  async listBans(
    request: operations.ListGuildBansRequest,
    options?: RequestOptions,
  ): Promise<Array<components.GuildBanResponse>> {
    return unwrapAsync(guildsListBans(
      this,
      request,
      options,
    ));
  }

  async setMfaLevel(
    request: operations.SetGuildMfaLevelRequest,
    options?: RequestOptions,
  ): Promise<components.GuildMFALevelResponse> {
    return unwrapAsync(guildsSetMfaLevel(
      this,
      request,
      options,
    ));
  }

  async get(
    request: operations.GetGuildRequest,
    options?: RequestOptions,
  ): Promise<components.GuildWithCountsResponse> {
    return unwrapAsync(guildsGet(
      this,
      request,
      options,
    ));
  }

  async delete(
    request: operations.DeleteGuildRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(guildsDelete(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.UpdateGuildRequest,
    options?: RequestOptions,
  ): Promise<components.GuildResponse> {
    return unwrapAsync(guildsUpdate(
      this,
      request,
      options,
    ));
  }
}
