/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { threadMembersDelete } from "../funcs/threadMembersDelete.js";
import { threadMembersGet } from "../funcs/threadMembersGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ThreadMembers extends ClientSDK {
  async get(
    request: operations.GetThreadMemberRequest,
    options?: RequestOptions,
  ): Promise<components.ThreadMemberResponse> {
    return unwrapAsync(threadMembersGet(
      this,
      request,
      options,
    ));
  }

  async delete(
    request: operations.DeleteThreadMemberRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(threadMembersDelete(
      this,
      request,
      options,
    ));
  }
}
