/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhookMessagesDeleteOriginal } from "../funcs/webhookMessagesDeleteOriginal.js";
import { webhookMessagesUpdateForm } from "../funcs/webhookMessagesUpdateForm.js";
import { webhookMessagesUpdateJson } from "../funcs/webhookMessagesUpdateJson.js";
import { webhookMessagesUpdateMultipart } from "../funcs/webhookMessagesUpdateMultipart.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class WebhookMessages extends ClientSDK {
  async deleteOriginal(
    request: operations.DeleteOriginalWebhookMessageRequest,
    security?: operations.DeleteOriginalWebhookMessageSecurity | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(webhookMessagesDeleteOriginal(
      this,
      request,
      security,
      options,
    ));
  }

  async updateMultipart(
    request: operations.UpdateWebhookMessageMultipartRequest,
    security?: operations.UpdateWebhookMessageMultipartSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.MessageResponse> {
    return unwrapAsync(webhookMessagesUpdateMultipart(
      this,
      request,
      security,
      options,
    ));
  }

  async updateJson(
    request: operations.UpdateWebhookMessageJsonRequest,
    security?: operations.UpdateWebhookMessageJsonSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.MessageResponse> {
    return unwrapAsync(webhookMessagesUpdateJson(
      this,
      request,
      security,
      options,
    ));
  }

  async updateForm(
    request: operations.UpdateWebhookMessageFormRequest,
    security?: operations.UpdateWebhookMessageFormSecurity | undefined,
    options?: RequestOptions,
  ): Promise<components.MessageResponse> {
    return unwrapAsync(webhookMessagesUpdateForm(
      this,
      request,
      security,
      options,
    ));
  }
}
