/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BotPartnerSDKTokenRequestBody = {
  provisionalUserId?: string | null | undefined;
  externalUserId: string;
  preferredGlobalName?: string | null | undefined;
};

export type BotPartnerSDKTokenResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ProvisionalTokenResponse;
};

/** @internal */
export const BotPartnerSDKTokenRequestBody$inboundSchema: z.ZodType<
  BotPartnerSDKTokenRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  provisional_user_id: z.nullable(z.string()).optional(),
  external_user_id: z.string(),
  preferred_global_name: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "provisional_user_id": "provisionalUserId",
    "external_user_id": "externalUserId",
    "preferred_global_name": "preferredGlobalName",
  });
});
/** @internal */
export type BotPartnerSDKTokenRequestBody$Outbound = {
  provisional_user_id?: string | null | undefined;
  external_user_id: string;
  preferred_global_name?: string | null | undefined;
};

/** @internal */
export const BotPartnerSDKTokenRequestBody$outboundSchema: z.ZodType<
  BotPartnerSDKTokenRequestBody$Outbound,
  z.ZodTypeDef,
  BotPartnerSDKTokenRequestBody
> = z.object({
  provisionalUserId: z.nullable(z.string()).optional(),
  externalUserId: z.string(),
  preferredGlobalName: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    provisionalUserId: "provisional_user_id",
    externalUserId: "external_user_id",
    preferredGlobalName: "preferred_global_name",
  });
});

export function botPartnerSDKTokenRequestBodyToJSON(
  botPartnerSDKTokenRequestBody: BotPartnerSDKTokenRequestBody,
): string {
  return JSON.stringify(
    BotPartnerSDKTokenRequestBody$outboundSchema.parse(
      botPartnerSDKTokenRequestBody,
    ),
  );
}
export function botPartnerSDKTokenRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<BotPartnerSDKTokenRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BotPartnerSDKTokenRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BotPartnerSDKTokenRequestBody' from JSON`,
  );
}

/** @internal */
export const BotPartnerSDKTokenResponse$inboundSchema: z.ZodType<
  BotPartnerSDKTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.ProvisionalTokenResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type BotPartnerSDKTokenResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ProvisionalTokenResponse$Outbound;
};

/** @internal */
export const BotPartnerSDKTokenResponse$outboundSchema: z.ZodType<
  BotPartnerSDKTokenResponse$Outbound,
  z.ZodTypeDef,
  BotPartnerSDKTokenResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ProvisionalTokenResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function botPartnerSDKTokenResponseToJSON(
  botPartnerSDKTokenResponse: BotPartnerSDKTokenResponse,
): string {
  return JSON.stringify(
    BotPartnerSDKTokenResponse$outboundSchema.parse(botPartnerSDKTokenResponse),
  );
}
export function botPartnerSDKTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<BotPartnerSDKTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BotPartnerSDKTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BotPartnerSDKTokenResponse' from JSON`,
  );
}
