/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BulkUpdateLobbyMembersRequest = {
  lobbyId: string;
  requestBody: Array<components.BulkLobbyMemberRequest> | null;
};

export type BulkUpdateLobbyMembersResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<components.LobbyMemberResponse>;
};

/** @internal */
export const BulkUpdateLobbyMembersRequest$inboundSchema: z.ZodType<
  BulkUpdateLobbyMembersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  lobby_id: z.string(),
  RequestBody: z.nullable(
    z.array(components.BulkLobbyMemberRequest$inboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    "lobby_id": "lobbyId",
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type BulkUpdateLobbyMembersRequest$Outbound = {
  lobby_id: string;
  RequestBody: Array<components.BulkLobbyMemberRequest$Outbound> | null;
};

/** @internal */
export const BulkUpdateLobbyMembersRequest$outboundSchema: z.ZodType<
  BulkUpdateLobbyMembersRequest$Outbound,
  z.ZodTypeDef,
  BulkUpdateLobbyMembersRequest
> = z.object({
  lobbyId: z.string(),
  requestBody: z.nullable(
    z.array(components.BulkLobbyMemberRequest$outboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    lobbyId: "lobby_id",
    requestBody: "RequestBody",
  });
});

export function bulkUpdateLobbyMembersRequestToJSON(
  bulkUpdateLobbyMembersRequest: BulkUpdateLobbyMembersRequest,
): string {
  return JSON.stringify(
    BulkUpdateLobbyMembersRequest$outboundSchema.parse(
      bulkUpdateLobbyMembersRequest,
    ),
  );
}
export function bulkUpdateLobbyMembersRequestFromJSON(
  jsonString: string,
): SafeParseResult<BulkUpdateLobbyMembersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkUpdateLobbyMembersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkUpdateLobbyMembersRequest' from JSON`,
  );
}

/** @internal */
export const BulkUpdateLobbyMembersResponse$inboundSchema: z.ZodType<
  BulkUpdateLobbyMembersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.array(components.LobbyMemberResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type BulkUpdateLobbyMembersResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: Array<components.LobbyMemberResponse$Outbound>;
};

/** @internal */
export const BulkUpdateLobbyMembersResponse$outboundSchema: z.ZodType<
  BulkUpdateLobbyMembersResponse$Outbound,
  z.ZodTypeDef,
  BulkUpdateLobbyMembersResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.array(components.LobbyMemberResponse$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function bulkUpdateLobbyMembersResponseToJSON(
  bulkUpdateLobbyMembersResponse: BulkUpdateLobbyMembersResponse,
): string {
  return JSON.stringify(
    BulkUpdateLobbyMembersResponse$outboundSchema.parse(
      bulkUpdateLobbyMembersResponse,
    ),
  );
}
export function bulkUpdateLobbyMembersResponseFromJSON(
  jsonString: string,
): SafeParseResult<BulkUpdateLobbyMembersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkUpdateLobbyMembersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkUpdateLobbyMembersResponse' from JSON`,
  );
}
