/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BulkUpdateGuildRolesRequest = {
  guildId: string;
  requestBody: Array<components.UpdateRolePositionsRequest>;
};

export type BulkUpdateGuildRolesResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<components.GuildRoleResponse>;
};

/** @internal */
export const BulkUpdateGuildRolesRequest$inboundSchema: z.ZodType<
  BulkUpdateGuildRolesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
  RequestBody: z.array(components.UpdateRolePositionsRequest$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type BulkUpdateGuildRolesRequest$Outbound = {
  guild_id: string;
  RequestBody: Array<components.UpdateRolePositionsRequest$Outbound>;
};

/** @internal */
export const BulkUpdateGuildRolesRequest$outboundSchema: z.ZodType<
  BulkUpdateGuildRolesRequest$Outbound,
  z.ZodTypeDef,
  BulkUpdateGuildRolesRequest
> = z.object({
  guildId: z.string(),
  requestBody: z.array(components.UpdateRolePositionsRequest$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BulkUpdateGuildRolesRequest$ {
  /** @deprecated use `BulkUpdateGuildRolesRequest$inboundSchema` instead. */
  export const inboundSchema = BulkUpdateGuildRolesRequest$inboundSchema;
  /** @deprecated use `BulkUpdateGuildRolesRequest$outboundSchema` instead. */
  export const outboundSchema = BulkUpdateGuildRolesRequest$outboundSchema;
  /** @deprecated use `BulkUpdateGuildRolesRequest$Outbound` instead. */
  export type Outbound = BulkUpdateGuildRolesRequest$Outbound;
}

export function bulkUpdateGuildRolesRequestToJSON(
  bulkUpdateGuildRolesRequest: BulkUpdateGuildRolesRequest,
): string {
  return JSON.stringify(
    BulkUpdateGuildRolesRequest$outboundSchema.parse(
      bulkUpdateGuildRolesRequest,
    ),
  );
}

export function bulkUpdateGuildRolesRequestFromJSON(
  jsonString: string,
): SafeParseResult<BulkUpdateGuildRolesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkUpdateGuildRolesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkUpdateGuildRolesRequest' from JSON`,
  );
}

/** @internal */
export const BulkUpdateGuildRolesResponse$inboundSchema: z.ZodType<
  BulkUpdateGuildRolesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.array(components.GuildRoleResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type BulkUpdateGuildRolesResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: Array<components.GuildRoleResponse$Outbound>;
};

/** @internal */
export const BulkUpdateGuildRolesResponse$outboundSchema: z.ZodType<
  BulkUpdateGuildRolesResponse$Outbound,
  z.ZodTypeDef,
  BulkUpdateGuildRolesResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.array(components.GuildRoleResponse$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BulkUpdateGuildRolesResponse$ {
  /** @deprecated use `BulkUpdateGuildRolesResponse$inboundSchema` instead. */
  export const inboundSchema = BulkUpdateGuildRolesResponse$inboundSchema;
  /** @deprecated use `BulkUpdateGuildRolesResponse$outboundSchema` instead. */
  export const outboundSchema = BulkUpdateGuildRolesResponse$outboundSchema;
  /** @deprecated use `BulkUpdateGuildRolesResponse$Outbound` instead. */
  export type Outbound = BulkUpdateGuildRolesResponse$Outbound;
}

export function bulkUpdateGuildRolesResponseToJSON(
  bulkUpdateGuildRolesResponse: BulkUpdateGuildRolesResponse,
): string {
  return JSON.stringify(
    BulkUpdateGuildRolesResponse$outboundSchema.parse(
      bulkUpdateGuildRolesResponse,
    ),
  );
}

export function bulkUpdateGuildRolesResponseFromJSON(
  jsonString: string,
): SafeParseResult<BulkUpdateGuildRolesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkUpdateGuildRolesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkUpdateGuildRolesResponse' from JSON`,
  );
}
