/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BulkUpdateLobbyMembersRequest = {
  lobbyId: string;
  requestBody: Array<components.BulkLobbyMemberRequest> | null;
};

/** @internal */
export const BulkUpdateLobbyMembersRequest$inboundSchema: z.ZodType<
  BulkUpdateLobbyMembersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  lobby_id: z.string(),
  RequestBody: z.nullable(
    z.array(components.BulkLobbyMemberRequest$inboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    "lobby_id": "lobbyId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type BulkUpdateLobbyMembersRequest$Outbound = {
  lobby_id: string;
  RequestBody: Array<components.BulkLobbyMemberRequest$Outbound> | null;
};

/** @internal */
export const BulkUpdateLobbyMembersRequest$outboundSchema: z.ZodType<
  BulkUpdateLobbyMembersRequest$Outbound,
  z.ZodTypeDef,
  BulkUpdateLobbyMembersRequest
> = z.object({
  lobbyId: z.string(),
  requestBody: z.nullable(
    z.array(components.BulkLobbyMemberRequest$outboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    lobbyId: "lobby_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BulkUpdateLobbyMembersRequest$ {
  /** @deprecated use `BulkUpdateLobbyMembersRequest$inboundSchema` instead. */
  export const inboundSchema = BulkUpdateLobbyMembersRequest$inboundSchema;
  /** @deprecated use `BulkUpdateLobbyMembersRequest$outboundSchema` instead. */
  export const outboundSchema = BulkUpdateLobbyMembersRequest$outboundSchema;
  /** @deprecated use `BulkUpdateLobbyMembersRequest$Outbound` instead. */
  export type Outbound = BulkUpdateLobbyMembersRequest$Outbound;
}

export function bulkUpdateLobbyMembersRequestToJSON(
  bulkUpdateLobbyMembersRequest: BulkUpdateLobbyMembersRequest,
): string {
  return JSON.stringify(
    BulkUpdateLobbyMembersRequest$outboundSchema.parse(
      bulkUpdateLobbyMembersRequest,
    ),
  );
}

export function bulkUpdateLobbyMembersRequestFromJSON(
  jsonString: string,
): SafeParseResult<BulkUpdateLobbyMembersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkUpdateLobbyMembersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkUpdateLobbyMembersRequest' from JSON`,
  );
}
