/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateMessageJsonRequest = {
  channelId: string;
  messageCreateRequest: components.MessageCreateRequest;
};

export type CreateMessageJsonResponse = {
  headers: { [k: string]: Array<string> };
  result: components.MessageResponse;
};

/** @internal */
export const CreateMessageJsonRequest$inboundSchema: z.ZodType<
  CreateMessageJsonRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  MessageCreateRequest: components.MessageCreateRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "MessageCreateRequest": "messageCreateRequest",
  });
});

/** @internal */
export type CreateMessageJsonRequest$Outbound = {
  channel_id: string;
  MessageCreateRequest: components.MessageCreateRequest$Outbound;
};

/** @internal */
export const CreateMessageJsonRequest$outboundSchema: z.ZodType<
  CreateMessageJsonRequest$Outbound,
  z.ZodTypeDef,
  CreateMessageJsonRequest
> = z.object({
  channelId: z.string(),
  messageCreateRequest: components.MessageCreateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    messageCreateRequest: "MessageCreateRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateMessageJsonRequest$ {
  /** @deprecated use `CreateMessageJsonRequest$inboundSchema` instead. */
  export const inboundSchema = CreateMessageJsonRequest$inboundSchema;
  /** @deprecated use `CreateMessageJsonRequest$outboundSchema` instead. */
  export const outboundSchema = CreateMessageJsonRequest$outboundSchema;
  /** @deprecated use `CreateMessageJsonRequest$Outbound` instead. */
  export type Outbound = CreateMessageJsonRequest$Outbound;
}

export function createMessageJsonRequestToJSON(
  createMessageJsonRequest: CreateMessageJsonRequest,
): string {
  return JSON.stringify(
    CreateMessageJsonRequest$outboundSchema.parse(createMessageJsonRequest),
  );
}

export function createMessageJsonRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateMessageJsonRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateMessageJsonRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateMessageJsonRequest' from JSON`,
  );
}

/** @internal */
export const CreateMessageJsonResponse$inboundSchema: z.ZodType<
  CreateMessageJsonResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.MessageResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type CreateMessageJsonResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.MessageResponse$Outbound;
};

/** @internal */
export const CreateMessageJsonResponse$outboundSchema: z.ZodType<
  CreateMessageJsonResponse$Outbound,
  z.ZodTypeDef,
  CreateMessageJsonResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.MessageResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateMessageJsonResponse$ {
  /** @deprecated use `CreateMessageJsonResponse$inboundSchema` instead. */
  export const inboundSchema = CreateMessageJsonResponse$inboundSchema;
  /** @deprecated use `CreateMessageJsonResponse$outboundSchema` instead. */
  export const outboundSchema = CreateMessageJsonResponse$outboundSchema;
  /** @deprecated use `CreateMessageJsonResponse$Outbound` instead. */
  export type Outbound = CreateMessageJsonResponse$Outbound;
}

export function createMessageJsonResponseToJSON(
  createMessageJsonResponse: CreateMessageJsonResponse,
): string {
  return JSON.stringify(
    CreateMessageJsonResponse$outboundSchema.parse(createMessageJsonResponse),
  );
}

export function createMessageJsonResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateMessageJsonResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateMessageJsonResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateMessageJsonResponse' from JSON`,
  );
}
