/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreatePinRequest = {
  channelId: string;
  messageId: string;
};

export type CreatePinResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const CreatePinRequest$inboundSchema: z.ZodType<
  CreatePinRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  message_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "message_id": "messageId",
  });
});

/** @internal */
export type CreatePinRequest$Outbound = {
  channel_id: string;
  message_id: string;
};

/** @internal */
export const CreatePinRequest$outboundSchema: z.ZodType<
  CreatePinRequest$Outbound,
  z.ZodTypeDef,
  CreatePinRequest
> = z.object({
  channelId: z.string(),
  messageId: z.string(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    messageId: "message_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatePinRequest$ {
  /** @deprecated use `CreatePinRequest$inboundSchema` instead. */
  export const inboundSchema = CreatePinRequest$inboundSchema;
  /** @deprecated use `CreatePinRequest$outboundSchema` instead. */
  export const outboundSchema = CreatePinRequest$outboundSchema;
  /** @deprecated use `CreatePinRequest$Outbound` instead. */
  export type Outbound = CreatePinRequest$Outbound;
}

export function createPinRequestToJSON(
  createPinRequest: CreatePinRequest,
): string {
  return JSON.stringify(
    CreatePinRequest$outboundSchema.parse(createPinRequest),
  );
}

export function createPinRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreatePinRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePinRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePinRequest' from JSON`,
  );
}

/** @internal */
export const CreatePinResponse$inboundSchema: z.ZodType<
  CreatePinResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

/** @internal */
export type CreatePinResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const CreatePinResponse$outboundSchema: z.ZodType<
  CreatePinResponse$Outbound,
  z.ZodTypeDef,
  CreatePinResponse
> = z.object({
  headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatePinResponse$ {
  /** @deprecated use `CreatePinResponse$inboundSchema` instead. */
  export const inboundSchema = CreatePinResponse$inboundSchema;
  /** @deprecated use `CreatePinResponse$outboundSchema` instead. */
  export const outboundSchema = CreatePinResponse$outboundSchema;
  /** @deprecated use `CreatePinResponse$Outbound` instead. */
  export type Outbound = CreatePinResponse$Outbound;
}

export function createPinResponseToJSON(
  createPinResponse: CreatePinResponse,
): string {
  return JSON.stringify(
    CreatePinResponse$outboundSchema.parse(createPinResponse),
  );
}

export function createPinResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePinResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePinResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePinResponse' from JSON`,
  );
}
