/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateGuildApplicationCommandSecurity = {
  botToken?: string | undefined;
};

export type CreateGuildApplicationCommandRequest = {
  applicationId: string;
  guildId: string;
  applicationCommandCreateRequest: components.ApplicationCommandCreateRequest;
};

export type CreateGuildApplicationCommandResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApplicationCommandResponse;
};

/** @internal */
export const CreateGuildApplicationCommandSecurity$inboundSchema: z.ZodType<
  CreateGuildApplicationCommandSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  BotToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "BotToken": "botToken",
  });
});
/** @internal */
export type CreateGuildApplicationCommandSecurity$Outbound = {
  BotToken?: string | undefined;
};

/** @internal */
export const CreateGuildApplicationCommandSecurity$outboundSchema: z.ZodType<
  CreateGuildApplicationCommandSecurity$Outbound,
  z.ZodTypeDef,
  CreateGuildApplicationCommandSecurity
> = z.object({
  botToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    botToken: "BotToken",
  });
});

export function createGuildApplicationCommandSecurityToJSON(
  createGuildApplicationCommandSecurity: CreateGuildApplicationCommandSecurity,
): string {
  return JSON.stringify(
    CreateGuildApplicationCommandSecurity$outboundSchema.parse(
      createGuildApplicationCommandSecurity,
    ),
  );
}
export function createGuildApplicationCommandSecurityFromJSON(
  jsonString: string,
): SafeParseResult<CreateGuildApplicationCommandSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateGuildApplicationCommandSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGuildApplicationCommandSecurity' from JSON`,
  );
}

/** @internal */
export const CreateGuildApplicationCommandRequest$inboundSchema: z.ZodType<
  CreateGuildApplicationCommandRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  application_id: z.string(),
  guild_id: z.string(),
  ApplicationCommandCreateRequest:
    components.ApplicationCommandCreateRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "application_id": "applicationId",
    "guild_id": "guildId",
    "ApplicationCommandCreateRequest": "applicationCommandCreateRequest",
  });
});
/** @internal */
export type CreateGuildApplicationCommandRequest$Outbound = {
  application_id: string;
  guild_id: string;
  ApplicationCommandCreateRequest:
    components.ApplicationCommandCreateRequest$Outbound;
};

/** @internal */
export const CreateGuildApplicationCommandRequest$outboundSchema: z.ZodType<
  CreateGuildApplicationCommandRequest$Outbound,
  z.ZodTypeDef,
  CreateGuildApplicationCommandRequest
> = z.object({
  applicationId: z.string(),
  guildId: z.string(),
  applicationCommandCreateRequest:
    components.ApplicationCommandCreateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    applicationId: "application_id",
    guildId: "guild_id",
    applicationCommandCreateRequest: "ApplicationCommandCreateRequest",
  });
});

export function createGuildApplicationCommandRequestToJSON(
  createGuildApplicationCommandRequest: CreateGuildApplicationCommandRequest,
): string {
  return JSON.stringify(
    CreateGuildApplicationCommandRequest$outboundSchema.parse(
      createGuildApplicationCommandRequest,
    ),
  );
}
export function createGuildApplicationCommandRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateGuildApplicationCommandRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateGuildApplicationCommandRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGuildApplicationCommandRequest' from JSON`,
  );
}

/** @internal */
export const CreateGuildApplicationCommandResponse$inboundSchema: z.ZodType<
  CreateGuildApplicationCommandResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.ApplicationCommandResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type CreateGuildApplicationCommandResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApplicationCommandResponse$Outbound;
};

/** @internal */
export const CreateGuildApplicationCommandResponse$outboundSchema: z.ZodType<
  CreateGuildApplicationCommandResponse$Outbound,
  z.ZodTypeDef,
  CreateGuildApplicationCommandResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApplicationCommandResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function createGuildApplicationCommandResponseToJSON(
  createGuildApplicationCommandResponse: CreateGuildApplicationCommandResponse,
): string {
  return JSON.stringify(
    CreateGuildApplicationCommandResponse$outboundSchema.parse(
      createGuildApplicationCommandResponse,
    ),
  );
}
export function createGuildApplicationCommandResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateGuildApplicationCommandResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateGuildApplicationCommandResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGuildApplicationCommandResponse' from JSON`,
  );
}
