/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateMessageFormRequest = {
  channelId: string;
  messageCreateRequest: components.MessageCreateRequest;
};

export type CreateMessageFormResponse = {
  headers: { [k: string]: Array<string> };
  result: components.MessageResponse;
};

/** @internal */
export const CreateMessageFormRequest$inboundSchema: z.ZodType<
  CreateMessageFormRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  MessageCreateRequest: components.MessageCreateRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "MessageCreateRequest": "messageCreateRequest",
  });
});

/** @internal */
export type CreateMessageFormRequest$Outbound = {
  channel_id: string;
  MessageCreateRequest: components.MessageCreateRequest$Outbound;
};

/** @internal */
export const CreateMessageFormRequest$outboundSchema: z.ZodType<
  CreateMessageFormRequest$Outbound,
  z.ZodTypeDef,
  CreateMessageFormRequest
> = z.object({
  channelId: z.string(),
  messageCreateRequest: components.MessageCreateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    messageCreateRequest: "MessageCreateRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateMessageFormRequest$ {
  /** @deprecated use `CreateMessageFormRequest$inboundSchema` instead. */
  export const inboundSchema = CreateMessageFormRequest$inboundSchema;
  /** @deprecated use `CreateMessageFormRequest$outboundSchema` instead. */
  export const outboundSchema = CreateMessageFormRequest$outboundSchema;
  /** @deprecated use `CreateMessageFormRequest$Outbound` instead. */
  export type Outbound = CreateMessageFormRequest$Outbound;
}

export function createMessageFormRequestToJSON(
  createMessageFormRequest: CreateMessageFormRequest,
): string {
  return JSON.stringify(
    CreateMessageFormRequest$outboundSchema.parse(createMessageFormRequest),
  );
}

export function createMessageFormRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateMessageFormRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateMessageFormRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateMessageFormRequest' from JSON`,
  );
}

/** @internal */
export const CreateMessageFormResponse$inboundSchema: z.ZodType<
  CreateMessageFormResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.MessageResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type CreateMessageFormResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.MessageResponse$Outbound;
};

/** @internal */
export const CreateMessageFormResponse$outboundSchema: z.ZodType<
  CreateMessageFormResponse$Outbound,
  z.ZodTypeDef,
  CreateMessageFormResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.MessageResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateMessageFormResponse$ {
  /** @deprecated use `CreateMessageFormResponse$inboundSchema` instead. */
  export const inboundSchema = CreateMessageFormResponse$inboundSchema;
  /** @deprecated use `CreateMessageFormResponse$outboundSchema` instead. */
  export const outboundSchema = CreateMessageFormResponse$outboundSchema;
  /** @deprecated use `CreateMessageFormResponse$Outbound` instead. */
  export type Outbound = CreateMessageFormResponse$Outbound;
}

export function createMessageFormResponseToJSON(
  createMessageFormResponse: CreateMessageFormResponse,
): string {
  return JSON.stringify(
    CreateMessageFormResponse$outboundSchema.parse(createMessageFormResponse),
  );
}

export function createMessageFormResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateMessageFormResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateMessageFormResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateMessageFormResponse' from JSON`,
  );
}
