/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateThreadFromMessageRequest = {
  channelId: string;
  messageId: string;
  createTextThreadWithMessageRequest:
    components.CreateTextThreadWithMessageRequest;
};

export type CreateThreadFromMessageResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ThreadResponse;
};

/** @internal */
export const CreateThreadFromMessageRequest$inboundSchema: z.ZodType<
  CreateThreadFromMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  message_id: z.string(),
  CreateTextThreadWithMessageRequest:
    components.CreateTextThreadWithMessageRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "message_id": "messageId",
    "CreateTextThreadWithMessageRequest": "createTextThreadWithMessageRequest",
  });
});

/** @internal */
export type CreateThreadFromMessageRequest$Outbound = {
  channel_id: string;
  message_id: string;
  CreateTextThreadWithMessageRequest:
    components.CreateTextThreadWithMessageRequest$Outbound;
};

/** @internal */
export const CreateThreadFromMessageRequest$outboundSchema: z.ZodType<
  CreateThreadFromMessageRequest$Outbound,
  z.ZodTypeDef,
  CreateThreadFromMessageRequest
> = z.object({
  channelId: z.string(),
  messageId: z.string(),
  createTextThreadWithMessageRequest:
    components.CreateTextThreadWithMessageRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    messageId: "message_id",
    createTextThreadWithMessageRequest: "CreateTextThreadWithMessageRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateThreadFromMessageRequest$ {
  /** @deprecated use `CreateThreadFromMessageRequest$inboundSchema` instead. */
  export const inboundSchema = CreateThreadFromMessageRequest$inboundSchema;
  /** @deprecated use `CreateThreadFromMessageRequest$outboundSchema` instead. */
  export const outboundSchema = CreateThreadFromMessageRequest$outboundSchema;
  /** @deprecated use `CreateThreadFromMessageRequest$Outbound` instead. */
  export type Outbound = CreateThreadFromMessageRequest$Outbound;
}

export function createThreadFromMessageRequestToJSON(
  createThreadFromMessageRequest: CreateThreadFromMessageRequest,
): string {
  return JSON.stringify(
    CreateThreadFromMessageRequest$outboundSchema.parse(
      createThreadFromMessageRequest,
    ),
  );
}

export function createThreadFromMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateThreadFromMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateThreadFromMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateThreadFromMessageRequest' from JSON`,
  );
}

/** @internal */
export const CreateThreadFromMessageResponse$inboundSchema: z.ZodType<
  CreateThreadFromMessageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ThreadResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type CreateThreadFromMessageResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ThreadResponse$Outbound;
};

/** @internal */
export const CreateThreadFromMessageResponse$outboundSchema: z.ZodType<
  CreateThreadFromMessageResponse$Outbound,
  z.ZodTypeDef,
  CreateThreadFromMessageResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ThreadResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateThreadFromMessageResponse$ {
  /** @deprecated use `CreateThreadFromMessageResponse$inboundSchema` instead. */
  export const inboundSchema = CreateThreadFromMessageResponse$inboundSchema;
  /** @deprecated use `CreateThreadFromMessageResponse$outboundSchema` instead. */
  export const outboundSchema = CreateThreadFromMessageResponse$outboundSchema;
  /** @deprecated use `CreateThreadFromMessageResponse$Outbound` instead. */
  export type Outbound = CreateThreadFromMessageResponse$Outbound;
}

export function createThreadFromMessageResponseToJSON(
  createThreadFromMessageResponse: CreateThreadFromMessageResponse,
): string {
  return JSON.stringify(
    CreateThreadFromMessageResponse$outboundSchema.parse(
      createThreadFromMessageResponse,
    ),
  );
}

export function createThreadFromMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateThreadFromMessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateThreadFromMessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateThreadFromMessageResponse' from JSON`,
  );
}
