/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteChannelRequest = {
  channelId: string;
};

/**
 * 200 response for delete_channel
 */
export type DeleteChannelResponseBody =
  | components.ThreadResponse
  | components.PrivateGroupChannelResponse
  | components.GuildChannelResponse
  | components.PrivateChannelResponse;

export type DeleteChannelResponse = {
  headers: { [k: string]: Array<string> };
  result:
    | components.ThreadResponse
    | components.PrivateGroupChannelResponse
    | components.GuildChannelResponse
    | components.PrivateChannelResponse;
};

/** @internal */
export const DeleteChannelRequest$inboundSchema: z.ZodType<
  DeleteChannelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
  });
});
/** @internal */
export type DeleteChannelRequest$Outbound = {
  channel_id: string;
};

/** @internal */
export const DeleteChannelRequest$outboundSchema: z.ZodType<
  DeleteChannelRequest$Outbound,
  z.ZodTypeDef,
  DeleteChannelRequest
> = z.object({
  channelId: z.string(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
  });
});

export function deleteChannelRequestToJSON(
  deleteChannelRequest: DeleteChannelRequest,
): string {
  return JSON.stringify(
    DeleteChannelRequest$outboundSchema.parse(deleteChannelRequest),
  );
}
export function deleteChannelRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteChannelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteChannelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteChannelRequest' from JSON`,
  );
}

/** @internal */
export const DeleteChannelResponseBody$inboundSchema: z.ZodType<
  DeleteChannelResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.ThreadResponse$inboundSchema,
  components.PrivateGroupChannelResponse$inboundSchema,
  components.GuildChannelResponse$inboundSchema,
  components.PrivateChannelResponse$inboundSchema,
]);
/** @internal */
export type DeleteChannelResponseBody$Outbound =
  | components.ThreadResponse$Outbound
  | components.PrivateGroupChannelResponse$Outbound
  | components.GuildChannelResponse$Outbound
  | components.PrivateChannelResponse$Outbound;

/** @internal */
export const DeleteChannelResponseBody$outboundSchema: z.ZodType<
  DeleteChannelResponseBody$Outbound,
  z.ZodTypeDef,
  DeleteChannelResponseBody
> = z.union([
  components.ThreadResponse$outboundSchema,
  components.PrivateGroupChannelResponse$outboundSchema,
  components.GuildChannelResponse$outboundSchema,
  components.PrivateChannelResponse$outboundSchema,
]);

export function deleteChannelResponseBodyToJSON(
  deleteChannelResponseBody: DeleteChannelResponseBody,
): string {
  return JSON.stringify(
    DeleteChannelResponseBody$outboundSchema.parse(deleteChannelResponseBody),
  );
}
export function deleteChannelResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteChannelResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteChannelResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteChannelResponseBody' from JSON`,
  );
}

/** @internal */
export const DeleteChannelResponse$inboundSchema: z.ZodType<
  DeleteChannelResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    components.ThreadResponse$inboundSchema,
    components.PrivateGroupChannelResponse$inboundSchema,
    components.GuildChannelResponse$inboundSchema,
    components.PrivateChannelResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type DeleteChannelResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    | components.ThreadResponse$Outbound
    | components.PrivateGroupChannelResponse$Outbound
    | components.GuildChannelResponse$Outbound
    | components.PrivateChannelResponse$Outbound;
};

/** @internal */
export const DeleteChannelResponse$outboundSchema: z.ZodType<
  DeleteChannelResponse$Outbound,
  z.ZodTypeDef,
  DeleteChannelResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.union([
    components.ThreadResponse$outboundSchema,
    components.PrivateGroupChannelResponse$outboundSchema,
    components.GuildChannelResponse$outboundSchema,
    components.PrivateChannelResponse$outboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function deleteChannelResponseToJSON(
  deleteChannelResponse: DeleteChannelResponse,
): string {
  return JSON.stringify(
    DeleteChannelResponse$outboundSchema.parse(deleteChannelResponse),
  );
}
export function deleteChannelResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteChannelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteChannelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteChannelResponse' from JSON`,
  );
}
