/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteGuildScheduledEventRequest = {
  guildId: string;
  guildScheduledEventId: string;
};

export type DeleteGuildScheduledEventResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const DeleteGuildScheduledEventRequest$inboundSchema: z.ZodType<
  DeleteGuildScheduledEventRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
  guild_scheduled_event_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
    "guild_scheduled_event_id": "guildScheduledEventId",
  });
});

/** @internal */
export type DeleteGuildScheduledEventRequest$Outbound = {
  guild_id: string;
  guild_scheduled_event_id: string;
};

/** @internal */
export const DeleteGuildScheduledEventRequest$outboundSchema: z.ZodType<
  DeleteGuildScheduledEventRequest$Outbound,
  z.ZodTypeDef,
  DeleteGuildScheduledEventRequest
> = z.object({
  guildId: z.string(),
  guildScheduledEventId: z.string(),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
    guildScheduledEventId: "guild_scheduled_event_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteGuildScheduledEventRequest$ {
  /** @deprecated use `DeleteGuildScheduledEventRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteGuildScheduledEventRequest$inboundSchema;
  /** @deprecated use `DeleteGuildScheduledEventRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteGuildScheduledEventRequest$outboundSchema;
  /** @deprecated use `DeleteGuildScheduledEventRequest$Outbound` instead. */
  export type Outbound = DeleteGuildScheduledEventRequest$Outbound;
}

export function deleteGuildScheduledEventRequestToJSON(
  deleteGuildScheduledEventRequest: DeleteGuildScheduledEventRequest,
): string {
  return JSON.stringify(
    DeleteGuildScheduledEventRequest$outboundSchema.parse(
      deleteGuildScheduledEventRequest,
    ),
  );
}

export function deleteGuildScheduledEventRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteGuildScheduledEventRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteGuildScheduledEventRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteGuildScheduledEventRequest' from JSON`,
  );
}

/** @internal */
export const DeleteGuildScheduledEventResponse$inboundSchema: z.ZodType<
  DeleteGuildScheduledEventResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

/** @internal */
export type DeleteGuildScheduledEventResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const DeleteGuildScheduledEventResponse$outboundSchema: z.ZodType<
  DeleteGuildScheduledEventResponse$Outbound,
  z.ZodTypeDef,
  DeleteGuildScheduledEventResponse
> = z.object({
  headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteGuildScheduledEventResponse$ {
  /** @deprecated use `DeleteGuildScheduledEventResponse$inboundSchema` instead. */
  export const inboundSchema = DeleteGuildScheduledEventResponse$inboundSchema;
  /** @deprecated use `DeleteGuildScheduledEventResponse$outboundSchema` instead. */
  export const outboundSchema =
    DeleteGuildScheduledEventResponse$outboundSchema;
  /** @deprecated use `DeleteGuildScheduledEventResponse$Outbound` instead. */
  export type Outbound = DeleteGuildScheduledEventResponse$Outbound;
}

export function deleteGuildScheduledEventResponseToJSON(
  deleteGuildScheduledEventResponse: DeleteGuildScheduledEventResponse,
): string {
  return JSON.stringify(
    DeleteGuildScheduledEventResponse$outboundSchema.parse(
      deleteGuildScheduledEventResponse,
    ),
  );
}

export function deleteGuildScheduledEventResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteGuildScheduledEventResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteGuildScheduledEventResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteGuildScheduledEventResponse' from JSON`,
  );
}
