/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeprecatedListPinsRequest = {
  channelId: string;
};

export type DeprecatedListPinsResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<components.MessageResponse>;
};

/** @internal */
export const DeprecatedListPinsRequest$inboundSchema: z.ZodType<
  DeprecatedListPinsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
  });
});

/** @internal */
export type DeprecatedListPinsRequest$Outbound = {
  channel_id: string;
};

/** @internal */
export const DeprecatedListPinsRequest$outboundSchema: z.ZodType<
  DeprecatedListPinsRequest$Outbound,
  z.ZodTypeDef,
  DeprecatedListPinsRequest
> = z.object({
  channelId: z.string(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeprecatedListPinsRequest$ {
  /** @deprecated use `DeprecatedListPinsRequest$inboundSchema` instead. */
  export const inboundSchema = DeprecatedListPinsRequest$inboundSchema;
  /** @deprecated use `DeprecatedListPinsRequest$outboundSchema` instead. */
  export const outboundSchema = DeprecatedListPinsRequest$outboundSchema;
  /** @deprecated use `DeprecatedListPinsRequest$Outbound` instead. */
  export type Outbound = DeprecatedListPinsRequest$Outbound;
}

export function deprecatedListPinsRequestToJSON(
  deprecatedListPinsRequest: DeprecatedListPinsRequest,
): string {
  return JSON.stringify(
    DeprecatedListPinsRequest$outboundSchema.parse(deprecatedListPinsRequest),
  );
}

export function deprecatedListPinsRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeprecatedListPinsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeprecatedListPinsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeprecatedListPinsRequest' from JSON`,
  );
}

/** @internal */
export const DeprecatedListPinsResponse$inboundSchema: z.ZodType<
  DeprecatedListPinsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.array(components.MessageResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type DeprecatedListPinsResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: Array<components.MessageResponse$Outbound>;
};

/** @internal */
export const DeprecatedListPinsResponse$outboundSchema: z.ZodType<
  DeprecatedListPinsResponse$Outbound,
  z.ZodTypeDef,
  DeprecatedListPinsResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.array(components.MessageResponse$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeprecatedListPinsResponse$ {
  /** @deprecated use `DeprecatedListPinsResponse$inboundSchema` instead. */
  export const inboundSchema = DeprecatedListPinsResponse$inboundSchema;
  /** @deprecated use `DeprecatedListPinsResponse$outboundSchema` instead. */
  export const outboundSchema = DeprecatedListPinsResponse$outboundSchema;
  /** @deprecated use `DeprecatedListPinsResponse$Outbound` instead. */
  export type Outbound = DeprecatedListPinsResponse$Outbound;
}

export function deprecatedListPinsResponseToJSON(
  deprecatedListPinsResponse: DeprecatedListPinsResponse,
): string {
  return JSON.stringify(
    DeprecatedListPinsResponse$outboundSchema.parse(deprecatedListPinsResponse),
  );
}

export function deprecatedListPinsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeprecatedListPinsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeprecatedListPinsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeprecatedListPinsResponse' from JSON`,
  );
}
