/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetActiveGuildThreadsRequest = {
  guildId: string;
};

export type GetActiveGuildThreadsResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ThreadsResponse;
};

/** @internal */
export const GetActiveGuildThreadsRequest$inboundSchema: z.ZodType<
  GetActiveGuildThreadsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
  });
});
/** @internal */
export type GetActiveGuildThreadsRequest$Outbound = {
  guild_id: string;
};

/** @internal */
export const GetActiveGuildThreadsRequest$outboundSchema: z.ZodType<
  GetActiveGuildThreadsRequest$Outbound,
  z.ZodTypeDef,
  GetActiveGuildThreadsRequest
> = z.object({
  guildId: z.string(),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
  });
});

export function getActiveGuildThreadsRequestToJSON(
  getActiveGuildThreadsRequest: GetActiveGuildThreadsRequest,
): string {
  return JSON.stringify(
    GetActiveGuildThreadsRequest$outboundSchema.parse(
      getActiveGuildThreadsRequest,
    ),
  );
}
export function getActiveGuildThreadsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetActiveGuildThreadsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActiveGuildThreadsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActiveGuildThreadsRequest' from JSON`,
  );
}

/** @internal */
export const GetActiveGuildThreadsResponse$inboundSchema: z.ZodType<
  GetActiveGuildThreadsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.ThreadsResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type GetActiveGuildThreadsResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ThreadsResponse$Outbound;
};

/** @internal */
export const GetActiveGuildThreadsResponse$outboundSchema: z.ZodType<
  GetActiveGuildThreadsResponse$Outbound,
  z.ZodTypeDef,
  GetActiveGuildThreadsResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ThreadsResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function getActiveGuildThreadsResponseToJSON(
  getActiveGuildThreadsResponse: GetActiveGuildThreadsResponse,
): string {
  return JSON.stringify(
    GetActiveGuildThreadsResponse$outboundSchema.parse(
      getActiveGuildThreadsResponse,
    ),
  );
}
export function getActiveGuildThreadsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetActiveGuildThreadsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActiveGuildThreadsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActiveGuildThreadsResponse' from JSON`,
  );
}
