/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetBotGatewayResponse = {
  headers: { [k: string]: Array<string> };
  result: components.GatewayBotResponse;
};

/** @internal */
export const GetBotGatewayResponse$inboundSchema: z.ZodType<
  GetBotGatewayResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.GatewayBotResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type GetBotGatewayResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.GatewayBotResponse$Outbound;
};

/** @internal */
export const GetBotGatewayResponse$outboundSchema: z.ZodType<
  GetBotGatewayResponse$Outbound,
  z.ZodTypeDef,
  GetBotGatewayResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.GatewayBotResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function getBotGatewayResponseToJSON(
  getBotGatewayResponse: GetBotGatewayResponse,
): string {
  return JSON.stringify(
    GetBotGatewayResponse$outboundSchema.parse(getBotGatewayResponse),
  );
}
export function getBotGatewayResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBotGatewayResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBotGatewayResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBotGatewayResponse' from JSON`,
  );
}
