/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetChannelRequest = {
  channelId: string;
};

/**
 * 200 response for get_channel
 */
export type GetChannelResponseBody =
  | components.ThreadResponse
  | components.PrivateGroupChannelResponse
  | components.GuildChannelResponse
  | components.PrivateChannelResponse;

export type GetChannelResponse = {
  headers: { [k: string]: Array<string> };
  result:
    | components.ThreadResponse
    | components.PrivateGroupChannelResponse
    | components.GuildChannelResponse
    | components.PrivateChannelResponse;
};

/** @internal */
export const GetChannelRequest$inboundSchema: z.ZodType<
  GetChannelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
  });
});
/** @internal */
export type GetChannelRequest$Outbound = {
  channel_id: string;
};

/** @internal */
export const GetChannelRequest$outboundSchema: z.ZodType<
  GetChannelRequest$Outbound,
  z.ZodTypeDef,
  GetChannelRequest
> = z.object({
  channelId: z.string(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
  });
});

export function getChannelRequestToJSON(
  getChannelRequest: GetChannelRequest,
): string {
  return JSON.stringify(
    GetChannelRequest$outboundSchema.parse(getChannelRequest),
  );
}
export function getChannelRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetChannelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetChannelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetChannelRequest' from JSON`,
  );
}

/** @internal */
export const GetChannelResponseBody$inboundSchema: z.ZodType<
  GetChannelResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.ThreadResponse$inboundSchema,
  components.PrivateGroupChannelResponse$inboundSchema,
  components.GuildChannelResponse$inboundSchema,
  components.PrivateChannelResponse$inboundSchema,
]);
/** @internal */
export type GetChannelResponseBody$Outbound =
  | components.ThreadResponse$Outbound
  | components.PrivateGroupChannelResponse$Outbound
  | components.GuildChannelResponse$Outbound
  | components.PrivateChannelResponse$Outbound;

/** @internal */
export const GetChannelResponseBody$outboundSchema: z.ZodType<
  GetChannelResponseBody$Outbound,
  z.ZodTypeDef,
  GetChannelResponseBody
> = z.union([
  components.ThreadResponse$outboundSchema,
  components.PrivateGroupChannelResponse$outboundSchema,
  components.GuildChannelResponse$outboundSchema,
  components.PrivateChannelResponse$outboundSchema,
]);

export function getChannelResponseBodyToJSON(
  getChannelResponseBody: GetChannelResponseBody,
): string {
  return JSON.stringify(
    GetChannelResponseBody$outboundSchema.parse(getChannelResponseBody),
  );
}
export function getChannelResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetChannelResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetChannelResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetChannelResponseBody' from JSON`,
  );
}

/** @internal */
export const GetChannelResponse$inboundSchema: z.ZodType<
  GetChannelResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    components.ThreadResponse$inboundSchema,
    components.PrivateGroupChannelResponse$inboundSchema,
    components.GuildChannelResponse$inboundSchema,
    components.PrivateChannelResponse$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type GetChannelResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    | components.ThreadResponse$Outbound
    | components.PrivateGroupChannelResponse$Outbound
    | components.GuildChannelResponse$Outbound
    | components.PrivateChannelResponse$Outbound;
};

/** @internal */
export const GetChannelResponse$outboundSchema: z.ZodType<
  GetChannelResponse$Outbound,
  z.ZodTypeDef,
  GetChannelResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.union([
    components.ThreadResponse$outboundSchema,
    components.PrivateGroupChannelResponse$outboundSchema,
    components.GuildChannelResponse$outboundSchema,
    components.PrivateChannelResponse$outboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function getChannelResponseToJSON(
  getChannelResponse: GetChannelResponse,
): string {
  return JSON.stringify(
    GetChannelResponse$outboundSchema.parse(getChannelResponse),
  );
}
export function getChannelResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetChannelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetChannelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetChannelResponse' from JSON`,
  );
}
