/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LeaveThreadRequest = {
  channelId: string;
};

export type LeaveThreadResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const LeaveThreadRequest$inboundSchema: z.ZodType<
  LeaveThreadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
  });
});
/** @internal */
export type LeaveThreadRequest$Outbound = {
  channel_id: string;
};

/** @internal */
export const LeaveThreadRequest$outboundSchema: z.ZodType<
  LeaveThreadRequest$Outbound,
  z.ZodTypeDef,
  LeaveThreadRequest
> = z.object({
  channelId: z.string(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
  });
});

export function leaveThreadRequestToJSON(
  leaveThreadRequest: LeaveThreadRequest,
): string {
  return JSON.stringify(
    LeaveThreadRequest$outboundSchema.parse(leaveThreadRequest),
  );
}
export function leaveThreadRequestFromJSON(
  jsonString: string,
): SafeParseResult<LeaveThreadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LeaveThreadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LeaveThreadRequest' from JSON`,
  );
}

/** @internal */
export const LeaveThreadResponse$inboundSchema: z.ZodType<
  LeaveThreadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});
/** @internal */
export type LeaveThreadResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const LeaveThreadResponse$outboundSchema: z.ZodType<
  LeaveThreadResponse$Outbound,
  z.ZodTypeDef,
  LeaveThreadResponse
> = z.object({
  headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
  });
});

export function leaveThreadResponseToJSON(
  leaveThreadResponse: LeaveThreadResponse,
): string {
  return JSON.stringify(
    LeaveThreadResponse$outboundSchema.parse(leaveThreadResponse),
  );
}
export function leaveThreadResponseFromJSON(
  jsonString: string,
): SafeParseResult<LeaveThreadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LeaveThreadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LeaveThreadResponse' from JSON`,
  );
}
