/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListPinsRequest = {
  channelId: string;
  before?: Date | undefined;
  limit?: number | undefined;
};

export type ListPinsResponse = {
  headers: { [k: string]: Array<string> };
  result: components.PinnedMessagesResponse;
};

/** @internal */
export const ListPinsRequest$inboundSchema: z.ZodType<
  ListPinsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  before: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  limit: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
  });
});
/** @internal */
export type ListPinsRequest$Outbound = {
  channel_id: string;
  before?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const ListPinsRequest$outboundSchema: z.ZodType<
  ListPinsRequest$Outbound,
  z.ZodTypeDef,
  ListPinsRequest
> = z.object({
  channelId: z.string(),
  before: z.date().transform(v => v.toISOString()).optional(),
  limit: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
  });
});

export function listPinsRequestToJSON(
  listPinsRequest: ListPinsRequest,
): string {
  return JSON.stringify(ListPinsRequest$outboundSchema.parse(listPinsRequest));
}
export function listPinsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListPinsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPinsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPinsRequest' from JSON`,
  );
}

/** @internal */
export const ListPinsResponse$inboundSchema: z.ZodType<
  ListPinsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.PinnedMessagesResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type ListPinsResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.PinnedMessagesResponse$Outbound;
};

/** @internal */
export const ListPinsResponse$outboundSchema: z.ZodType<
  ListPinsResponse$Outbound,
  z.ZodTypeDef,
  ListPinsResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.PinnedMessagesResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function listPinsResponseToJSON(
  listPinsResponse: ListPinsResponse,
): string {
  return JSON.stringify(
    ListPinsResponse$outboundSchema.parse(listPinsResponse),
  );
}
export function listPinsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPinsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPinsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPinsResponse' from JSON`,
  );
}
