/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListChannelInvitesRequest = {
  channelId: string;
};

export type ResponseBody =
  | components.GuildInviteResponse
  | components.GroupDMInviteResponse
  | components.FriendInviteResponse;

export type ListChannelInvitesResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<
    | components.GuildInviteResponse
    | components.GroupDMInviteResponse
    | components.FriendInviteResponse
    | null
  >;
};

/** @internal */
export const ListChannelInvitesRequest$inboundSchema: z.ZodType<
  ListChannelInvitesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
  });
});

/** @internal */
export type ListChannelInvitesRequest$Outbound = {
  channel_id: string;
};

/** @internal */
export const ListChannelInvitesRequest$outboundSchema: z.ZodType<
  ListChannelInvitesRequest$Outbound,
  z.ZodTypeDef,
  ListChannelInvitesRequest
> = z.object({
  channelId: z.string(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListChannelInvitesRequest$ {
  /** @deprecated use `ListChannelInvitesRequest$inboundSchema` instead. */
  export const inboundSchema = ListChannelInvitesRequest$inboundSchema;
  /** @deprecated use `ListChannelInvitesRequest$outboundSchema` instead. */
  export const outboundSchema = ListChannelInvitesRequest$outboundSchema;
  /** @deprecated use `ListChannelInvitesRequest$Outbound` instead. */
  export type Outbound = ListChannelInvitesRequest$Outbound;
}

export function listChannelInvitesRequestToJSON(
  listChannelInvitesRequest: ListChannelInvitesRequest,
): string {
  return JSON.stringify(
    ListChannelInvitesRequest$outboundSchema.parse(listChannelInvitesRequest),
  );
}

export function listChannelInvitesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListChannelInvitesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListChannelInvitesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListChannelInvitesRequest' from JSON`,
  );
}

/** @internal */
export const ResponseBody$inboundSchema: z.ZodType<
  ResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.GuildInviteResponse$inboundSchema,
  components.GroupDMInviteResponse$inboundSchema,
  components.FriendInviteResponse$inboundSchema,
]);

/** @internal */
export type ResponseBody$Outbound =
  | components.GuildInviteResponse$Outbound
  | components.GroupDMInviteResponse$Outbound
  | components.FriendInviteResponse$Outbound;

/** @internal */
export const ResponseBody$outboundSchema: z.ZodType<
  ResponseBody$Outbound,
  z.ZodTypeDef,
  ResponseBody
> = z.union([
  components.GuildInviteResponse$outboundSchema,
  components.GroupDMInviteResponse$outboundSchema,
  components.FriendInviteResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseBody$ {
  /** @deprecated use `ResponseBody$inboundSchema` instead. */
  export const inboundSchema = ResponseBody$inboundSchema;
  /** @deprecated use `ResponseBody$outboundSchema` instead. */
  export const outboundSchema = ResponseBody$outboundSchema;
  /** @deprecated use `ResponseBody$Outbound` instead. */
  export type Outbound = ResponseBody$Outbound;
}

export function responseBodyToJSON(responseBody: ResponseBody): string {
  return JSON.stringify(ResponseBody$outboundSchema.parse(responseBody));
}

export function responseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseBody' from JSON`,
  );
}

/** @internal */
export const ListChannelInvitesResponse$inboundSchema: z.ZodType<
  ListChannelInvitesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.array(
    z.nullable(
      z.union([
        components.GuildInviteResponse$inboundSchema,
        components.GroupDMInviteResponse$inboundSchema,
        components.FriendInviteResponse$inboundSchema,
      ]),
    ),
  ),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type ListChannelInvitesResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: Array<
    | components.GuildInviteResponse$Outbound
    | components.GroupDMInviteResponse$Outbound
    | components.FriendInviteResponse$Outbound
    | null
  >;
};

/** @internal */
export const ListChannelInvitesResponse$outboundSchema: z.ZodType<
  ListChannelInvitesResponse$Outbound,
  z.ZodTypeDef,
  ListChannelInvitesResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.array(
    z.nullable(
      z.union([
        components.GuildInviteResponse$outboundSchema,
        components.GroupDMInviteResponse$outboundSchema,
        components.FriendInviteResponse$outboundSchema,
      ]),
    ),
  ),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListChannelInvitesResponse$ {
  /** @deprecated use `ListChannelInvitesResponse$inboundSchema` instead. */
  export const inboundSchema = ListChannelInvitesResponse$inboundSchema;
  /** @deprecated use `ListChannelInvitesResponse$outboundSchema` instead. */
  export const outboundSchema = ListChannelInvitesResponse$outboundSchema;
  /** @deprecated use `ListChannelInvitesResponse$Outbound` instead. */
  export type Outbound = ListChannelInvitesResponse$Outbound;
}

export function listChannelInvitesResponseToJSON(
  listChannelInvitesResponse: ListChannelInvitesResponse,
): string {
  return JSON.stringify(
    ListChannelInvitesResponse$outboundSchema.parse(listChannelInvitesResponse),
  );
}

export function listChannelInvitesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListChannelInvitesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListChannelInvitesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListChannelInvitesResponse' from JSON`,
  );
}
