/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListGuildScheduledEventExceptionUsersRequest = {
  guildId: string;
  guildScheduledEventId: string;
  guildScheduledEventExceptionId: string;
  withMember?: boolean | undefined;
  limit?: number | undefined;
  before?: string | undefined;
  after?: string | undefined;
};

export type ListGuildScheduledEventExceptionUsersResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<components.ScheduledEventUserResponse>;
};

/** @internal */
export const ListGuildScheduledEventExceptionUsersRequest$inboundSchema:
  z.ZodType<
    ListGuildScheduledEventExceptionUsersRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    guild_id: z.string(),
    guild_scheduled_event_id: z.string(),
    guild_scheduled_event_exception_id: z.string(),
    with_member: z.boolean().optional(),
    limit: z.number().int().optional(),
    before: z.string().optional(),
    after: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "guild_id": "guildId",
      "guild_scheduled_event_id": "guildScheduledEventId",
      "guild_scheduled_event_exception_id": "guildScheduledEventExceptionId",
      "with_member": "withMember",
    });
  });
/** @internal */
export type ListGuildScheduledEventExceptionUsersRequest$Outbound = {
  guild_id: string;
  guild_scheduled_event_id: string;
  guild_scheduled_event_exception_id: string;
  with_member?: boolean | undefined;
  limit?: number | undefined;
  before?: string | undefined;
  after?: string | undefined;
};

/** @internal */
export const ListGuildScheduledEventExceptionUsersRequest$outboundSchema:
  z.ZodType<
    ListGuildScheduledEventExceptionUsersRequest$Outbound,
    z.ZodTypeDef,
    ListGuildScheduledEventExceptionUsersRequest
  > = z.object({
    guildId: z.string(),
    guildScheduledEventId: z.string(),
    guildScheduledEventExceptionId: z.string(),
    withMember: z.boolean().optional(),
    limit: z.number().int().optional(),
    before: z.string().optional(),
    after: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      guildId: "guild_id",
      guildScheduledEventId: "guild_scheduled_event_id",
      guildScheduledEventExceptionId: "guild_scheduled_event_exception_id",
      withMember: "with_member",
    });
  });

export function listGuildScheduledEventExceptionUsersRequestToJSON(
  listGuildScheduledEventExceptionUsersRequest:
    ListGuildScheduledEventExceptionUsersRequest,
): string {
  return JSON.stringify(
    ListGuildScheduledEventExceptionUsersRequest$outboundSchema.parse(
      listGuildScheduledEventExceptionUsersRequest,
    ),
  );
}
export function listGuildScheduledEventExceptionUsersRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  ListGuildScheduledEventExceptionUsersRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListGuildScheduledEventExceptionUsersRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListGuildScheduledEventExceptionUsersRequest' from JSON`,
  );
}

/** @internal */
export const ListGuildScheduledEventExceptionUsersResponse$inboundSchema:
  z.ZodType<
    ListGuildScheduledEventExceptionUsersResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: z.array(components.ScheduledEventUserResponse$inboundSchema),
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });
/** @internal */
export type ListGuildScheduledEventExceptionUsersResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: Array<components.ScheduledEventUserResponse$Outbound>;
};

/** @internal */
export const ListGuildScheduledEventExceptionUsersResponse$outboundSchema:
  z.ZodType<
    ListGuildScheduledEventExceptionUsersResponse$Outbound,
    z.ZodTypeDef,
    ListGuildScheduledEventExceptionUsersResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: z.array(components.ScheduledEventUserResponse$outboundSchema),
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

export function listGuildScheduledEventExceptionUsersResponseToJSON(
  listGuildScheduledEventExceptionUsersResponse:
    ListGuildScheduledEventExceptionUsersResponse,
): string {
  return JSON.stringify(
    ListGuildScheduledEventExceptionUsersResponse$outboundSchema.parse(
      listGuildScheduledEventExceptionUsersResponse,
    ),
  );
}
export function listGuildScheduledEventExceptionUsersResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListGuildScheduledEventExceptionUsersResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListGuildScheduledEventExceptionUsersResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListGuildScheduledEventExceptionUsersResponse' from JSON`,
  );
}
