/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SendSoundboardSoundRequest = {
  channelId: string;
  soundboardSoundSendRequest: components.SoundboardSoundSendRequest;
};

export type SendSoundboardSoundResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const SendSoundboardSoundRequest$inboundSchema: z.ZodType<
  SendSoundboardSoundRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  SoundboardSoundSendRequest:
    components.SoundboardSoundSendRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "SoundboardSoundSendRequest": "soundboardSoundSendRequest",
  });
});

/** @internal */
export type SendSoundboardSoundRequest$Outbound = {
  channel_id: string;
  SoundboardSoundSendRequest: components.SoundboardSoundSendRequest$Outbound;
};

/** @internal */
export const SendSoundboardSoundRequest$outboundSchema: z.ZodType<
  SendSoundboardSoundRequest$Outbound,
  z.ZodTypeDef,
  SendSoundboardSoundRequest
> = z.object({
  channelId: z.string(),
  soundboardSoundSendRequest:
    components.SoundboardSoundSendRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    soundboardSoundSendRequest: "SoundboardSoundSendRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SendSoundboardSoundRequest$ {
  /** @deprecated use `SendSoundboardSoundRequest$inboundSchema` instead. */
  export const inboundSchema = SendSoundboardSoundRequest$inboundSchema;
  /** @deprecated use `SendSoundboardSoundRequest$outboundSchema` instead. */
  export const outboundSchema = SendSoundboardSoundRequest$outboundSchema;
  /** @deprecated use `SendSoundboardSoundRequest$Outbound` instead. */
  export type Outbound = SendSoundboardSoundRequest$Outbound;
}

export function sendSoundboardSoundRequestToJSON(
  sendSoundboardSoundRequest: SendSoundboardSoundRequest,
): string {
  return JSON.stringify(
    SendSoundboardSoundRequest$outboundSchema.parse(sendSoundboardSoundRequest),
  );
}

export function sendSoundboardSoundRequestFromJSON(
  jsonString: string,
): SafeParseResult<SendSoundboardSoundRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendSoundboardSoundRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendSoundboardSoundRequest' from JSON`,
  );
}

/** @internal */
export const SendSoundboardSoundResponse$inboundSchema: z.ZodType<
  SendSoundboardSoundResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

/** @internal */
export type SendSoundboardSoundResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const SendSoundboardSoundResponse$outboundSchema: z.ZodType<
  SendSoundboardSoundResponse$Outbound,
  z.ZodTypeDef,
  SendSoundboardSoundResponse
> = z.object({
  headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SendSoundboardSoundResponse$ {
  /** @deprecated use `SendSoundboardSoundResponse$inboundSchema` instead. */
  export const inboundSchema = SendSoundboardSoundResponse$inboundSchema;
  /** @deprecated use `SendSoundboardSoundResponse$outboundSchema` instead. */
  export const outboundSchema = SendSoundboardSoundResponse$outboundSchema;
  /** @deprecated use `SendSoundboardSoundResponse$Outbound` instead. */
  export type Outbound = SendSoundboardSoundResponse$Outbound;
}

export function sendSoundboardSoundResponseToJSON(
  sendSoundboardSoundResponse: SendSoundboardSoundResponse,
): string {
  return JSON.stringify(
    SendSoundboardSoundResponse$outboundSchema.parse(
      sendSoundboardSoundResponse,
    ),
  );
}

export function sendSoundboardSoundResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendSoundboardSoundResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendSoundboardSoundResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendSoundboardSoundResponse' from JSON`,
  );
}
