/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SyncGuildTemplateRequest = {
  guildId: string;
  code: string;
};

export type SyncGuildTemplateResponse = {
  headers: { [k: string]: Array<string> };
  result: components.GuildTemplateResponse;
};

/** @internal */
export const SyncGuildTemplateRequest$inboundSchema: z.ZodType<
  SyncGuildTemplateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
  code: z.string(),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
  });
});
/** @internal */
export type SyncGuildTemplateRequest$Outbound = {
  guild_id: string;
  code: string;
};

/** @internal */
export const SyncGuildTemplateRequest$outboundSchema: z.ZodType<
  SyncGuildTemplateRequest$Outbound,
  z.ZodTypeDef,
  SyncGuildTemplateRequest
> = z.object({
  guildId: z.string(),
  code: z.string(),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
  });
});

export function syncGuildTemplateRequestToJSON(
  syncGuildTemplateRequest: SyncGuildTemplateRequest,
): string {
  return JSON.stringify(
    SyncGuildTemplateRequest$outboundSchema.parse(syncGuildTemplateRequest),
  );
}
export function syncGuildTemplateRequestFromJSON(
  jsonString: string,
): SafeParseResult<SyncGuildTemplateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SyncGuildTemplateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SyncGuildTemplateRequest' from JSON`,
  );
}

/** @internal */
export const SyncGuildTemplateResponse$inboundSchema: z.ZodType<
  SyncGuildTemplateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.GuildTemplateResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type SyncGuildTemplateResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.GuildTemplateResponse$Outbound;
};

/** @internal */
export const SyncGuildTemplateResponse$outboundSchema: z.ZodType<
  SyncGuildTemplateResponse$Outbound,
  z.ZodTypeDef,
  SyncGuildTemplateResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.GuildTemplateResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function syncGuildTemplateResponseToJSON(
  syncGuildTemplateResponse: SyncGuildTemplateResponse,
): string {
  return JSON.stringify(
    SyncGuildTemplateResponse$outboundSchema.parse(syncGuildTemplateResponse),
  );
}
export function syncGuildTemplateResponseFromJSON(
  jsonString: string,
): SafeParseResult<SyncGuildTemplateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SyncGuildTemplateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SyncGuildTemplateResponse' from JSON`,
  );
}
