/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateApplicationUserRoleConnectionRequest = {
  applicationId: string;
  updateApplicationUserRoleConnectionRequest:
    components.UpdateApplicationUserRoleConnectionRequest;
};

export type UpdateApplicationUserRoleConnectionResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApplicationUserRoleConnectionResponse;
};

/** @internal */
export const UpdateApplicationUserRoleConnectionRequest$inboundSchema:
  z.ZodType<UpdateApplicationUserRoleConnectionRequest, z.ZodTypeDef, unknown> =
    z.object({
      application_id: z.string(),
      UpdateApplicationUserRoleConnectionRequest:
        components.UpdateApplicationUserRoleConnectionRequest$inboundSchema,
    }).transform((v) => {
      return remap$(v, {
        "application_id": "applicationId",
        "UpdateApplicationUserRoleConnectionRequest":
          "updateApplicationUserRoleConnectionRequest",
      });
    });
/** @internal */
export type UpdateApplicationUserRoleConnectionRequest$Outbound = {
  application_id: string;
  UpdateApplicationUserRoleConnectionRequest:
    components.UpdateApplicationUserRoleConnectionRequest$Outbound;
};

/** @internal */
export const UpdateApplicationUserRoleConnectionRequest$outboundSchema:
  z.ZodType<
    UpdateApplicationUserRoleConnectionRequest$Outbound,
    z.ZodTypeDef,
    UpdateApplicationUserRoleConnectionRequest
  > = z.object({
    applicationId: z.string(),
    updateApplicationUserRoleConnectionRequest:
      components.UpdateApplicationUserRoleConnectionRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      applicationId: "application_id",
      updateApplicationUserRoleConnectionRequest:
        "UpdateApplicationUserRoleConnectionRequest",
    });
  });

export function updateApplicationUserRoleConnectionRequestToJSON(
  updateApplicationUserRoleConnectionRequest:
    UpdateApplicationUserRoleConnectionRequest,
): string {
  return JSON.stringify(
    UpdateApplicationUserRoleConnectionRequest$outboundSchema.parse(
      updateApplicationUserRoleConnectionRequest,
    ),
  );
}
export function updateApplicationUserRoleConnectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateApplicationUserRoleConnectionRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateApplicationUserRoleConnectionRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateApplicationUserRoleConnectionRequest' from JSON`,
  );
}

/** @internal */
export const UpdateApplicationUserRoleConnectionResponse$inboundSchema:
  z.ZodType<
    UpdateApplicationUserRoleConnectionResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: components.ApplicationUserRoleConnectionResponse$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });
/** @internal */
export type UpdateApplicationUserRoleConnectionResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApplicationUserRoleConnectionResponse$Outbound;
};

/** @internal */
export const UpdateApplicationUserRoleConnectionResponse$outboundSchema:
  z.ZodType<
    UpdateApplicationUserRoleConnectionResponse$Outbound,
    z.ZodTypeDef,
    UpdateApplicationUserRoleConnectionResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: components.ApplicationUserRoleConnectionResponse$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

export function updateApplicationUserRoleConnectionResponseToJSON(
  updateApplicationUserRoleConnectionResponse:
    UpdateApplicationUserRoleConnectionResponse,
): string {
  return JSON.stringify(
    UpdateApplicationUserRoleConnectionResponse$outboundSchema.parse(
      updateApplicationUserRoleConnectionResponse,
    ),
  );
}
export function updateApplicationUserRoleConnectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateApplicationUserRoleConnectionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateApplicationUserRoleConnectionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateApplicationUserRoleConnectionResponse' from JSON`,
  );
}
