/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateMyUserResponse = {
  headers: { [k: string]: Array<string> };
  result: components.UserPIIResponse;
};

/** @internal */
export const UpdateMyUserResponse$inboundSchema: z.ZodType<
  UpdateMyUserResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.UserPIIResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type UpdateMyUserResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.UserPIIResponse$Outbound;
};

/** @internal */
export const UpdateMyUserResponse$outboundSchema: z.ZodType<
  UpdateMyUserResponse$Outbound,
  z.ZodTypeDef,
  UpdateMyUserResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.UserPIIResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function updateMyUserResponseToJSON(
  updateMyUserResponse: UpdateMyUserResponse,
): string {
  return JSON.stringify(
    UpdateMyUserResponse$outboundSchema.parse(updateMyUserResponse),
  );
}
export function updateMyUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateMyUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateMyUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateMyUserResponse' from JSON`,
  );
}
