/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateLobbyMessageExternalModerationMetadataRequest = {
  lobbyId: string;
  messageId: string;
  requestBody: { [k: string]: string };
};

export type UpdateLobbyMessageExternalModerationMetadataResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const UpdateLobbyMessageExternalModerationMetadataRequest$inboundSchema:
  z.ZodType<
    UpdateLobbyMessageExternalModerationMetadataRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    lobby_id: z.string(),
    message_id: z.string(),
    RequestBody: z.record(z.string()),
  }).transform((v) => {
    return remap$(v, {
      "lobby_id": "lobbyId",
      "message_id": "messageId",
      "RequestBody": "requestBody",
    });
  });
/** @internal */
export type UpdateLobbyMessageExternalModerationMetadataRequest$Outbound = {
  lobby_id: string;
  message_id: string;
  RequestBody: { [k: string]: string };
};

/** @internal */
export const UpdateLobbyMessageExternalModerationMetadataRequest$outboundSchema:
  z.ZodType<
    UpdateLobbyMessageExternalModerationMetadataRequest$Outbound,
    z.ZodTypeDef,
    UpdateLobbyMessageExternalModerationMetadataRequest
  > = z.object({
    lobbyId: z.string(),
    messageId: z.string(),
    requestBody: z.record(z.string()),
  }).transform((v) => {
    return remap$(v, {
      lobbyId: "lobby_id",
      messageId: "message_id",
      requestBody: "RequestBody",
    });
  });

export function updateLobbyMessageExternalModerationMetadataRequestToJSON(
  updateLobbyMessageExternalModerationMetadataRequest:
    UpdateLobbyMessageExternalModerationMetadataRequest,
): string {
  return JSON.stringify(
    UpdateLobbyMessageExternalModerationMetadataRequest$outboundSchema.parse(
      updateLobbyMessageExternalModerationMetadataRequest,
    ),
  );
}
export function updateLobbyMessageExternalModerationMetadataRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateLobbyMessageExternalModerationMetadataRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateLobbyMessageExternalModerationMetadataRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateLobbyMessageExternalModerationMetadataRequest' from JSON`,
  );
}

/** @internal */
export const UpdateLobbyMessageExternalModerationMetadataResponse$inboundSchema:
  z.ZodType<
    UpdateLobbyMessageExternalModerationMetadataResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
    });
  });
/** @internal */
export type UpdateLobbyMessageExternalModerationMetadataResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const UpdateLobbyMessageExternalModerationMetadataResponse$outboundSchema:
  z.ZodType<
    UpdateLobbyMessageExternalModerationMetadataResponse$Outbound,
    z.ZodTypeDef,
    UpdateLobbyMessageExternalModerationMetadataResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
    });
  });

export function updateLobbyMessageExternalModerationMetadataResponseToJSON(
  updateLobbyMessageExternalModerationMetadataResponse:
    UpdateLobbyMessageExternalModerationMetadataResponse,
): string {
  return JSON.stringify(
    UpdateLobbyMessageExternalModerationMetadataResponse$outboundSchema.parse(
      updateLobbyMessageExternalModerationMetadataResponse,
    ),
  );
}
export function updateLobbyMessageExternalModerationMetadataResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateLobbyMessageExternalModerationMetadataResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateLobbyMessageExternalModerationMetadataResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateLobbyMessageExternalModerationMetadataResponse' from JSON`,
  );
}
