/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TextInputComponentForModalRequest,
  TextInputComponentForModalRequest$inboundSchema,
  TextInputComponentForModalRequest$Outbound,
  TextInputComponentForModalRequest$outboundSchema,
} from "./textinputcomponentresponse.js";

/**
 * Container for other components
 */
export const ActionRowComponentForModalRequestType = {
  One: 1,
  Two: 2,
  Three: 3,
  Four: 4,
  Five: 5,
  Six: 6,
  Seven: 7,
  Eight: 8,
  Nine: 9,
  Ten: 10,
  Eleven: 11,
  Twelve: 12,
  Thirteen: 13,
  Fourteen: 14,
  Seventeen: 17,
  Eighteen: 18,
  Nineteen: 19,
  TwentyOne: 21,
  TwentyTwo: 22,
  TwentyThree: 23,
} as const;
/**
 * Container for other components
 */
export type ActionRowComponentForModalRequestType = ClosedEnum<
  typeof ActionRowComponentForModalRequestType
>;

export type ActionRowComponentForModalRequest = {
  type: ActionRowComponentForModalRequestType;
  id?: number | null | undefined;
  components: Array<TextInputComponentForModalRequest>;
};

/** @internal */
export const ActionRowComponentForModalRequestType$inboundSchema:
  z.ZodNativeEnum<typeof ActionRowComponentForModalRequestType> = z.nativeEnum(
    ActionRowComponentForModalRequestType,
  );
/** @internal */
export const ActionRowComponentForModalRequestType$outboundSchema:
  z.ZodNativeEnum<typeof ActionRowComponentForModalRequestType> =
    ActionRowComponentForModalRequestType$inboundSchema;

/** @internal */
export const ActionRowComponentForModalRequest$inboundSchema: z.ZodType<
  ActionRowComponentForModalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: ActionRowComponentForModalRequestType$inboundSchema,
  id: z.nullable(z.number().int()).optional(),
  components: z.array(TextInputComponentForModalRequest$inboundSchema),
});
/** @internal */
export type ActionRowComponentForModalRequest$Outbound = {
  type: number;
  id?: number | null | undefined;
  components: Array<TextInputComponentForModalRequest$Outbound>;
};

/** @internal */
export const ActionRowComponentForModalRequest$outboundSchema: z.ZodType<
  ActionRowComponentForModalRequest$Outbound,
  z.ZodTypeDef,
  ActionRowComponentForModalRequest
> = z.object({
  type: ActionRowComponentForModalRequestType$outboundSchema,
  id: z.nullable(z.number().int()).optional(),
  components: z.array(TextInputComponentForModalRequest$outboundSchema),
});

export function actionRowComponentForModalRequestToJSON(
  actionRowComponentForModalRequest: ActionRowComponentForModalRequest,
): string {
  return JSON.stringify(
    ActionRowComponentForModalRequest$outboundSchema.parse(
      actionRowComponentForModalRequest,
    ),
  );
}
export function actionRowComponentForModalRequestFromJSON(
  jsonString: string,
): SafeParseResult<ActionRowComponentForModalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionRowComponentForModalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionRowComponentForModalRequest' from JSON`,
  );
}
