/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AttachmentResponse,
  AttachmentResponse$inboundSchema,
  AttachmentResponse$Outbound,
  AttachmentResponse$outboundSchema,
} from "./attachmentresponse.js";

export type ActivitiesAttachmentResponse = {
  attachment: AttachmentResponse;
};

/** @internal */
export const ActivitiesAttachmentResponse$inboundSchema: z.ZodType<
  ActivitiesAttachmentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  attachment: AttachmentResponse$inboundSchema,
});
/** @internal */
export type ActivitiesAttachmentResponse$Outbound = {
  attachment: AttachmentResponse$Outbound;
};

/** @internal */
export const ActivitiesAttachmentResponse$outboundSchema: z.ZodType<
  ActivitiesAttachmentResponse$Outbound,
  z.ZodTypeDef,
  ActivitiesAttachmentResponse
> = z.object({
  attachment: AttachmentResponse$outboundSchema,
});

export function activitiesAttachmentResponseToJSON(
  activitiesAttachmentResponse: ActivitiesAttachmentResponse,
): string {
  return JSON.stringify(
    ActivitiesAttachmentResponse$outboundSchema.parse(
      activitiesAttachmentResponse,
    ),
  );
}
export function activitiesAttachmentResponseFromJSON(
  jsonString: string,
): SafeParseResult<ActivitiesAttachmentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivitiesAttachmentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivitiesAttachmentResponse' from JSON`,
  );
}
