/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * allows /users/@me without email
 */
export const Scopes = {
  Identify: "identify",
  Email: "email",
  Connections: "connections",
  Guilds: "guilds",
  GuildsJoin: "guilds.join",
  GuildsMembersRead: "guilds.members.read",
  GdmJoin: "gdm.join",
  Bot: "bot",
  Rpc: "rpc",
  RpcNotificationsRead: "rpc.notifications.read",
  RpcVoiceRead: "rpc.voice.read",
  RpcVoiceWrite: "rpc.voice.write",
  RpcVideoRead: "rpc.video.read",
  RpcVideoWrite: "rpc.video.write",
  RpcScreenshareRead: "rpc.screenshare.read",
  RpcScreenshareWrite: "rpc.screenshare.write",
  RpcActivitiesWrite: "rpc.activities.write",
  WebhookIncoming: "webhook.incoming",
  MessagesRead: "messages.read",
  ApplicationsBuildsUpload: "applications.builds.upload",
  ApplicationsBuildsRead: "applications.builds.read",
  ApplicationsCommands: "applications.commands",
  ApplicationsCommandsPermissionsUpdate:
    "applications.commands.permissions.update",
  ApplicationsCommandsUpdate: "applications.commands.update",
  ApplicationsStoreUpdate: "applications.store.update",
  ApplicationsEntitlements: "applications.entitlements",
  ActivitiesRead: "activities.read",
  ActivitiesWrite: "activities.write",
  ActivitiesInvitesWrite: "activities.invites.write",
  RelationshipsRead: "relationships.read",
  Voice: "voice",
  DmChannelsRead: "dm_channels.read",
  RoleConnectionsWrite: "role_connections.write",
  Openid: "openid",
} as const;
/**
 * allows /users/@me without email
 */
export type Scopes = ClosedEnum<typeof Scopes>;

export type ApplicationOAuth2InstallParamsResponse = {
  scopes: Array<Scopes>;
  permissions: string;
};

/** @internal */
export const Scopes$inboundSchema: z.ZodNativeEnum<typeof Scopes> = z
  .nativeEnum(Scopes);
/** @internal */
export const Scopes$outboundSchema: z.ZodNativeEnum<typeof Scopes> =
  Scopes$inboundSchema;

/** @internal */
export const ApplicationOAuth2InstallParamsResponse$inboundSchema: z.ZodType<
  ApplicationOAuth2InstallParamsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  scopes: z.array(Scopes$inboundSchema),
  permissions: z.string(),
});
/** @internal */
export type ApplicationOAuth2InstallParamsResponse$Outbound = {
  scopes: Array<string>;
  permissions: string;
};

/** @internal */
export const ApplicationOAuth2InstallParamsResponse$outboundSchema: z.ZodType<
  ApplicationOAuth2InstallParamsResponse$Outbound,
  z.ZodTypeDef,
  ApplicationOAuth2InstallParamsResponse
> = z.object({
  scopes: z.array(Scopes$outboundSchema),
  permissions: z.string(),
});

export function applicationOAuth2InstallParamsResponseToJSON(
  applicationOAuth2InstallParamsResponse:
    ApplicationOAuth2InstallParamsResponse,
): string {
  return JSON.stringify(
    ApplicationOAuth2InstallParamsResponse$outboundSchema.parse(
      applicationOAuth2InstallParamsResponse,
    ),
  );
}
export function applicationOAuth2InstallParamsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationOAuth2InstallParamsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationOAuth2InstallParamsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationOAuth2InstallParamsResponse' from JSON`,
  );
}
