/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuditLogObjectChangeResponse,
  AuditLogObjectChangeResponse$inboundSchema,
  AuditLogObjectChangeResponse$Outbound,
  AuditLogObjectChangeResponse$outboundSchema,
} from "./auditlogobjectchangeresponse.js";

/**
 * Scheduled event exception was created
 */
export const AuditLogActionTypes = {
  One: 1,
  Ten: 10,
  Eleven: 11,
  Twelve: 12,
  Thirteen: 13,
  Fourteen: 14,
  Fifteen: 15,
  Twenty: 20,
  TwentyOne: 21,
  TwentyTwo: 22,
  TwentyThree: 23,
  TwentyFour: 24,
  TwentyFive: 25,
  TwentySix: 26,
  TwentySeven: 27,
  TwentyEight: 28,
  Thirty: 30,
  ThirtyOne: 31,
  ThirtyTwo: 32,
  Forty: 40,
  FortyOne: 41,
  FortyTwo: 42,
  Fifty: 50,
  FiftyOne: 51,
  FiftyTwo: 52,
  Sixty: 60,
  SixtyOne: 61,
  SixtyTwo: 62,
  SeventyTwo: 72,
  SeventyThree: 73,
  SeventyFour: 74,
  SeventyFive: 75,
  Eighty: 80,
  EightyOne: 81,
  EightyTwo: 82,
  EightyThree: 83,
  EightyFour: 84,
  EightyFive: 85,
  Ninety: 90,
  NinetyOne: 91,
  NinetyTwo: 92,
  OneHundred: 100,
  OneHundredAndOne: 101,
  OneHundredAndTwo: 102,
  OneHundredAndTen: 110,
  OneHundredAndEleven: 111,
  OneHundredAndTwelve: 112,
  OneHundredAndTwentyOne: 121,
  OneHundredAndThirty: 130,
  OneHundredAndThirtyOne: 131,
  OneHundredAndThirtyTwo: 132,
  OneHundredAndForty: 140,
  OneHundredAndFortyOne: 141,
  OneHundredAndFortyTwo: 142,
  OneHundredAndFortyThree: 143,
  OneHundredAndFortyFour: 144,
  OneHundredAndFortyFive: 145,
  OneHundredAndFortySix: 146,
  OneHundredAndFifty: 150,
  OneHundredAndFiftyOne: 151,
  OneHundredAndSixtyThree: 163,
  OneHundredAndSixtyFour: 164,
  OneHundredAndSixtyFive: 165,
  OneHundredAndSixtySix: 166,
  OneHundredAndSixtySeven: 167,
  OneHundredAndSeventyOne: 171,
  OneHundredAndSeventyTwo: 172,
  OneHundredAndEighty: 180,
  OneHundredAndNinety: 190,
  OneHundredAndNinetyOne: 191,
  OneHundredAndNinetyTwo: 192,
  OneHundredAndNinetyThree: 193,
  TwoHundred: 200,
  TwoHundredAndOne: 201,
  TwoHundredAndTwo: 202,
  TwoHundredAndEleven: 211,
} as const;
/**
 * Scheduled event exception was created
 */
export type AuditLogActionTypes = ClosedEnum<typeof AuditLogActionTypes>;

export type AuditLogEntryResponse = {
  id: string;
  actionType: AuditLogActionTypes;
  userId: string | null;
  targetId: string | null;
  changes?: Array<AuditLogObjectChangeResponse> | undefined;
  options?: { [k: string]: string } | undefined;
  reason?: string | undefined;
};

/** @internal */
export const AuditLogActionTypes$inboundSchema: z.ZodNativeEnum<
  typeof AuditLogActionTypes
> = z.nativeEnum(AuditLogActionTypes);
/** @internal */
export const AuditLogActionTypes$outboundSchema: z.ZodNativeEnum<
  typeof AuditLogActionTypes
> = AuditLogActionTypes$inboundSchema;

/** @internal */
export const AuditLogEntryResponse$inboundSchema: z.ZodType<
  AuditLogEntryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  action_type: AuditLogActionTypes$inboundSchema,
  user_id: z.nullable(z.string()),
  target_id: z.nullable(z.string()),
  changes: z.array(AuditLogObjectChangeResponse$inboundSchema).optional(),
  options: z.record(z.string()).optional(),
  reason: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "action_type": "actionType",
    "user_id": "userId",
    "target_id": "targetId",
  });
});
/** @internal */
export type AuditLogEntryResponse$Outbound = {
  id: string;
  action_type: number;
  user_id: string | null;
  target_id: string | null;
  changes?: Array<AuditLogObjectChangeResponse$Outbound> | undefined;
  options?: { [k: string]: string } | undefined;
  reason?: string | undefined;
};

/** @internal */
export const AuditLogEntryResponse$outboundSchema: z.ZodType<
  AuditLogEntryResponse$Outbound,
  z.ZodTypeDef,
  AuditLogEntryResponse
> = z.object({
  id: z.string(),
  actionType: AuditLogActionTypes$outboundSchema,
  userId: z.nullable(z.string()),
  targetId: z.nullable(z.string()),
  changes: z.array(AuditLogObjectChangeResponse$outboundSchema).optional(),
  options: z.record(z.string()).optional(),
  reason: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    actionType: "action_type",
    userId: "user_id",
    targetId: "target_id",
  });
});

export function auditLogEntryResponseToJSON(
  auditLogEntryResponse: AuditLogEntryResponse,
): string {
  return JSON.stringify(
    AuditLogEntryResponse$outboundSchema.parse(auditLogEntryResponse),
  );
}
export function auditLogEntryResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuditLogEntryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditLogEntryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditLogEntryResponse' from JSON`,
  );
}
