/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ChannelPermissionOverwrites = {
  Zero: 0,
  One: 1,
} as const;
export type ChannelPermissionOverwrites = ClosedEnum<
  typeof ChannelPermissionOverwrites
>;

export type ChannelPermissionOverwriteResponse = {
  id: string;
  type: ChannelPermissionOverwrites;
  allow: string;
  deny: string;
};

export type ChannelPermissionOverwriteRequest = {
  id: string;
  type?: ChannelPermissionOverwrites | null | undefined;
  allow?: number | null | undefined;
  deny?: number | null | undefined;
};

/** @internal */
export const ChannelPermissionOverwrites$inboundSchema: z.ZodNativeEnum<
  typeof ChannelPermissionOverwrites
> = z.nativeEnum(ChannelPermissionOverwrites);
/** @internal */
export const ChannelPermissionOverwrites$outboundSchema: z.ZodNativeEnum<
  typeof ChannelPermissionOverwrites
> = ChannelPermissionOverwrites$inboundSchema;

/** @internal */
export const ChannelPermissionOverwriteResponse$inboundSchema: z.ZodType<
  ChannelPermissionOverwriteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: ChannelPermissionOverwrites$inboundSchema,
  allow: z.string(),
  deny: z.string(),
});
/** @internal */
export type ChannelPermissionOverwriteResponse$Outbound = {
  id: string;
  type: number;
  allow: string;
  deny: string;
};

/** @internal */
export const ChannelPermissionOverwriteResponse$outboundSchema: z.ZodType<
  ChannelPermissionOverwriteResponse$Outbound,
  z.ZodTypeDef,
  ChannelPermissionOverwriteResponse
> = z.object({
  id: z.string(),
  type: ChannelPermissionOverwrites$outboundSchema,
  allow: z.string(),
  deny: z.string(),
});

export function channelPermissionOverwriteResponseToJSON(
  channelPermissionOverwriteResponse: ChannelPermissionOverwriteResponse,
): string {
  return JSON.stringify(
    ChannelPermissionOverwriteResponse$outboundSchema.parse(
      channelPermissionOverwriteResponse,
    ),
  );
}
export function channelPermissionOverwriteResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChannelPermissionOverwriteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ChannelPermissionOverwriteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChannelPermissionOverwriteResponse' from JSON`,
  );
}

/** @internal */
export const ChannelPermissionOverwriteRequest$inboundSchema: z.ZodType<
  ChannelPermissionOverwriteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: z.nullable(ChannelPermissionOverwrites$inboundSchema).optional(),
  allow: z.nullable(z.number().int()).optional(),
  deny: z.nullable(z.number().int()).optional(),
});
/** @internal */
export type ChannelPermissionOverwriteRequest$Outbound = {
  id: string;
  type?: number | null | undefined;
  allow?: number | null | undefined;
  deny?: number | null | undefined;
};

/** @internal */
export const ChannelPermissionOverwriteRequest$outboundSchema: z.ZodType<
  ChannelPermissionOverwriteRequest$Outbound,
  z.ZodTypeDef,
  ChannelPermissionOverwriteRequest
> = z.object({
  id: z.string(),
  type: z.nullable(ChannelPermissionOverwrites$outboundSchema).optional(),
  allow: z.nullable(z.number().int()).optional(),
  deny: z.nullable(z.number().int()).optional(),
});

export function channelPermissionOverwriteRequestToJSON(
  channelPermissionOverwriteRequest: ChannelPermissionOverwriteRequest,
): string {
  return JSON.stringify(
    ChannelPermissionOverwriteRequest$outboundSchema.parse(
      channelPermissionOverwriteRequest,
    ),
  );
}
export function channelPermissionOverwriteRequestFromJSON(
  jsonString: string,
): SafeParseResult<ChannelPermissionOverwriteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChannelPermissionOverwriteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChannelPermissionOverwriteRequest' from JSON`,
  );
}
