/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ConnectedAccountIntegrationResponse,
  ConnectedAccountIntegrationResponse$inboundSchema,
  ConnectedAccountIntegrationResponse$Outbound,
  ConnectedAccountIntegrationResponse$outboundSchema,
} from "./connectedaccountintegrationresponse.js";

export const ConnectedAccountProviders = {
  Battlenet: "battlenet",
  Bluesky: "bluesky",
  Bungie: "bungie",
  Ebay: "ebay",
  Epicgames: "epicgames",
  Facebook: "facebook",
  Github: "github",
  Instagram: "instagram",
  Mastodon: "mastodon",
  Leagueoflegends: "leagueoflegends",
  Paypal: "paypal",
  Playstation: "playstation",
  Reddit: "reddit",
  Riotgames: "riotgames",
  Roblox: "roblox",
  Skype: "skype",
  Spotify: "spotify",
  Steam: "steam",
  Tiktok: "tiktok",
  Twitch: "twitch",
  Twitter: "twitter",
  Xbox: "xbox",
  Youtube: "youtube",
  Domain: "domain",
} as const;
export type ConnectedAccountProviders = ClosedEnum<
  typeof ConnectedAccountProviders
>;

export const ConnectedAccountVisibility = {
  Zero: 0,
  One: 1,
} as const;
export type ConnectedAccountVisibility = ClosedEnum<
  typeof ConnectedAccountVisibility
>;

export type ConnectedAccountResponse = {
  id: string;
  name: string | null;
  type: ConnectedAccountProviders;
  friendSync: boolean;
  integrations?: Array<ConnectedAccountIntegrationResponse> | undefined;
  showActivity: boolean;
  twoWayLink: boolean;
  verified: boolean;
  visibility: ConnectedAccountVisibility;
  revoked?: boolean | undefined;
};

/** @internal */
export const ConnectedAccountProviders$inboundSchema: z.ZodNativeEnum<
  typeof ConnectedAccountProviders
> = z.nativeEnum(ConnectedAccountProviders);
/** @internal */
export const ConnectedAccountProviders$outboundSchema: z.ZodNativeEnum<
  typeof ConnectedAccountProviders
> = ConnectedAccountProviders$inboundSchema;

/** @internal */
export const ConnectedAccountVisibility$inboundSchema: z.ZodNativeEnum<
  typeof ConnectedAccountVisibility
> = z.nativeEnum(ConnectedAccountVisibility);
/** @internal */
export const ConnectedAccountVisibility$outboundSchema: z.ZodNativeEnum<
  typeof ConnectedAccountVisibility
> = ConnectedAccountVisibility$inboundSchema;

/** @internal */
export const ConnectedAccountResponse$inboundSchema: z.ZodType<
  ConnectedAccountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()),
  type: ConnectedAccountProviders$inboundSchema,
  friend_sync: z.boolean(),
  integrations: z.array(ConnectedAccountIntegrationResponse$inboundSchema)
    .optional(),
  show_activity: z.boolean(),
  two_way_link: z.boolean(),
  verified: z.boolean(),
  visibility: ConnectedAccountVisibility$inboundSchema,
  revoked: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "friend_sync": "friendSync",
    "show_activity": "showActivity",
    "two_way_link": "twoWayLink",
  });
});
/** @internal */
export type ConnectedAccountResponse$Outbound = {
  id: string;
  name: string | null;
  type: string;
  friend_sync: boolean;
  integrations?:
    | Array<ConnectedAccountIntegrationResponse$Outbound>
    | undefined;
  show_activity: boolean;
  two_way_link: boolean;
  verified: boolean;
  visibility: number;
  revoked?: boolean | undefined;
};

/** @internal */
export const ConnectedAccountResponse$outboundSchema: z.ZodType<
  ConnectedAccountResponse$Outbound,
  z.ZodTypeDef,
  ConnectedAccountResponse
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()),
  type: ConnectedAccountProviders$outboundSchema,
  friendSync: z.boolean(),
  integrations: z.array(ConnectedAccountIntegrationResponse$outboundSchema)
    .optional(),
  showActivity: z.boolean(),
  twoWayLink: z.boolean(),
  verified: z.boolean(),
  visibility: ConnectedAccountVisibility$outboundSchema,
  revoked: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    friendSync: "friend_sync",
    showActivity: "show_activity",
    twoWayLink: "two_way_link",
  });
});

export function connectedAccountResponseToJSON(
  connectedAccountResponse: ConnectedAccountResponse,
): string {
  return JSON.stringify(
    ConnectedAccountResponse$outboundSchema.parse(connectedAccountResponse),
  );
}
export function connectedAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConnectedAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConnectedAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConnectedAccountResponse' from JSON`,
  );
}
