/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MessageResponse,
  MessageResponse$inboundSchema,
  MessageResponse$Outbound,
  MessageResponse$outboundSchema,
} from "./messageresponse.js";

export const CreateMessageInteractionCallbackResponseType = {
  One: 1,
  Four: 4,
  Five: 5,
  Six: 6,
  Seven: 7,
  Eight: 8,
  Nine: 9,
  Twelve: 12,
  Thirteen: 13,
} as const;
export type CreateMessageInteractionCallbackResponseType = ClosedEnum<
  typeof CreateMessageInteractionCallbackResponseType
>;

export type CreateMessageInteractionCallbackResponse = {
  type: CreateMessageInteractionCallbackResponseType;
  message: MessageResponse;
};

/** @internal */
export const CreateMessageInteractionCallbackResponseType$inboundSchema:
  z.ZodNativeEnum<typeof CreateMessageInteractionCallbackResponseType> = z
    .nativeEnum(CreateMessageInteractionCallbackResponseType);
/** @internal */
export const CreateMessageInteractionCallbackResponseType$outboundSchema:
  z.ZodNativeEnum<typeof CreateMessageInteractionCallbackResponseType> =
    CreateMessageInteractionCallbackResponseType$inboundSchema;

/** @internal */
export const CreateMessageInteractionCallbackResponse$inboundSchema: z.ZodType<
  CreateMessageInteractionCallbackResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: CreateMessageInteractionCallbackResponseType$inboundSchema,
  message: MessageResponse$inboundSchema,
});
/** @internal */
export type CreateMessageInteractionCallbackResponse$Outbound = {
  type: number;
  message: MessageResponse$Outbound;
};

/** @internal */
export const CreateMessageInteractionCallbackResponse$outboundSchema: z.ZodType<
  CreateMessageInteractionCallbackResponse$Outbound,
  z.ZodTypeDef,
  CreateMessageInteractionCallbackResponse
> = z.object({
  type: CreateMessageInteractionCallbackResponseType$outboundSchema,
  message: MessageResponse$outboundSchema,
});

export function createMessageInteractionCallbackResponseToJSON(
  createMessageInteractionCallbackResponse:
    CreateMessageInteractionCallbackResponse,
): string {
  return JSON.stringify(
    CreateMessageInteractionCallbackResponse$outboundSchema.parse(
      createMessageInteractionCallbackResponse,
    ),
  );
}
export function createMessageInteractionCallbackResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateMessageInteractionCallbackResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateMessageInteractionCallbackResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreateMessageInteractionCallbackResponse' from JSON`,
  );
}
