/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccountResponse,
  AccountResponse$inboundSchema,
  AccountResponse$Outbound,
  AccountResponse$outboundSchema,
} from "./accountresponse.js";

export const GuildSubscriptionIntegrationResponseType = {
  Discord: "discord",
  Twitch: "twitch",
  Youtube: "youtube",
  GuildSubscription: "guild_subscription",
} as const;
export type GuildSubscriptionIntegrationResponseType = ClosedEnum<
  typeof GuildSubscriptionIntegrationResponseType
>;

export type GuildSubscriptionIntegrationResponse = {
  type: GuildSubscriptionIntegrationResponseType;
  name: string | null;
  account: AccountResponse;
  enabled: boolean;
  id: string;
};

/** @internal */
export const GuildSubscriptionIntegrationResponseType$inboundSchema:
  z.ZodNativeEnum<typeof GuildSubscriptionIntegrationResponseType> = z
    .nativeEnum(GuildSubscriptionIntegrationResponseType);
/** @internal */
export const GuildSubscriptionIntegrationResponseType$outboundSchema:
  z.ZodNativeEnum<typeof GuildSubscriptionIntegrationResponseType> =
    GuildSubscriptionIntegrationResponseType$inboundSchema;

/** @internal */
export const GuildSubscriptionIntegrationResponse$inboundSchema: z.ZodType<
  GuildSubscriptionIntegrationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: GuildSubscriptionIntegrationResponseType$inboundSchema,
  name: z.nullable(z.string()),
  account: AccountResponse$inboundSchema,
  enabled: z.boolean(),
  id: z.string(),
});
/** @internal */
export type GuildSubscriptionIntegrationResponse$Outbound = {
  type: string;
  name: string | null;
  account: AccountResponse$Outbound;
  enabled: boolean;
  id: string;
};

/** @internal */
export const GuildSubscriptionIntegrationResponse$outboundSchema: z.ZodType<
  GuildSubscriptionIntegrationResponse$Outbound,
  z.ZodTypeDef,
  GuildSubscriptionIntegrationResponse
> = z.object({
  type: GuildSubscriptionIntegrationResponseType$outboundSchema,
  name: z.nullable(z.string()),
  account: AccountResponse$outboundSchema,
  enabled: z.boolean(),
  id: z.string(),
});

export function guildSubscriptionIntegrationResponseToJSON(
  guildSubscriptionIntegrationResponse: GuildSubscriptionIntegrationResponse,
): string {
  return JSON.stringify(
    GuildSubscriptionIntegrationResponse$outboundSchema.parse(
      guildSubscriptionIntegrationResponse,
    ),
  );
}
export function guildSubscriptionIntegrationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GuildSubscriptionIntegrationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GuildSubscriptionIntegrationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GuildSubscriptionIntegrationResponse' from JSON`,
  );
}
