/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  GuildWelcomeScreenChannelResponse,
  GuildWelcomeScreenChannelResponse$inboundSchema,
  GuildWelcomeScreenChannelResponse$Outbound,
  GuildWelcomeScreenChannelResponse$outboundSchema,
} from "./guildwelcomescreenchannelresponse.js";

export type GuildWelcomeScreenResponse = {
  description: string | null;
  welcomeChannels: Array<GuildWelcomeScreenChannelResponse>;
};

/** @internal */
export const GuildWelcomeScreenResponse$inboundSchema: z.ZodType<
  GuildWelcomeScreenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.nullable(z.string()),
  welcome_channels: z.array(GuildWelcomeScreenChannelResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "welcome_channels": "welcomeChannels",
  });
});
/** @internal */
export type GuildWelcomeScreenResponse$Outbound = {
  description: string | null;
  welcome_channels: Array<GuildWelcomeScreenChannelResponse$Outbound>;
};

/** @internal */
export const GuildWelcomeScreenResponse$outboundSchema: z.ZodType<
  GuildWelcomeScreenResponse$Outbound,
  z.ZodTypeDef,
  GuildWelcomeScreenResponse
> = z.object({
  description: z.nullable(z.string()),
  welcomeChannels: z.array(GuildWelcomeScreenChannelResponse$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    welcomeChannels: "welcome_channels",
  });
});

export function guildWelcomeScreenResponseToJSON(
  guildWelcomeScreenResponse: GuildWelcomeScreenResponse,
): string {
  return JSON.stringify(
    GuildWelcomeScreenResponse$outboundSchema.parse(guildWelcomeScreenResponse),
  );
}
export function guildWelcomeScreenResponseFromJSON(
  jsonString: string,
): SafeParseResult<GuildWelcomeScreenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GuildWelcomeScreenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GuildWelcomeScreenResponse' from JSON`,
  );
}
