/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  InviteApplicationResponse,
  InviteApplicationResponse$inboundSchema,
  InviteApplicationResponse$Outbound,
  InviteApplicationResponse$outboundSchema,
} from "./inviteapplicationresponse.js";
import {
  InviteChannelResponse,
  InviteChannelResponse$inboundSchema,
  InviteChannelResponse$Outbound,
  InviteChannelResponse$outboundSchema,
} from "./invitechannelresponse.js";
import {
  InviteGuildResponse,
  InviteGuildResponse$inboundSchema,
  InviteGuildResponse$Outbound,
  InviteGuildResponse$outboundSchema,
} from "./inviteguildresponse.js";
import {
  ScheduledEventResponse,
  ScheduledEventResponse$inboundSchema,
  ScheduledEventResponse$Outbound,
  ScheduledEventResponse$outboundSchema,
} from "./scheduledeventresponse.js";
import {
  UserResponse,
  UserResponse$inboundSchema,
  UserResponse$Outbound,
  UserResponse$outboundSchema,
} from "./userresponse.js";

export type GuildInviteResponse = {
  type?: 0 | undefined;
  code: string;
  inviter?: UserResponse | undefined;
  maxAge?: number | undefined;
  createdAt?: Date | undefined;
  expiresAt?: Date | null | undefined;
  isContact?: boolean | undefined;
  flags?: number | undefined;
  guild: InviteGuildResponse;
  guildId: string;
  channel: InviteChannelResponse;
  targetType?: 1 | undefined;
  targetUser?: UserResponse | undefined;
  targetApplication?: InviteApplicationResponse | undefined;
  guildScheduledEvent?: ScheduledEventResponse | undefined;
  uses?: number | undefined;
  maxUses?: number | undefined;
  temporary?: boolean | undefined;
  approximateMemberCount?: number | null | undefined;
  approximatePresenceCount?: number | null | undefined;
  isNicknameChangeable?: boolean | undefined;
};

/** @internal */
export const GuildInviteResponse$inboundSchema: z.ZodType<
  GuildInviteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal(0).optional(),
  code: z.string(),
  inviter: UserResponse$inboundSchema.optional(),
  max_age: z.number().int().optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  expires_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  is_contact: z.boolean().optional(),
  flags: z.number().int().optional(),
  guild: InviteGuildResponse$inboundSchema,
  guild_id: z.string(),
  channel: InviteChannelResponse$inboundSchema,
  target_type: z.literal(1).optional(),
  target_user: UserResponse$inboundSchema.optional(),
  target_application: InviteApplicationResponse$inboundSchema.optional(),
  guild_scheduled_event: ScheduledEventResponse$inboundSchema.optional(),
  uses: z.number().int().optional(),
  max_uses: z.number().int().optional(),
  temporary: z.boolean().optional(),
  approximate_member_count: z.nullable(z.number().int()).optional(),
  approximate_presence_count: z.nullable(z.number().int()).optional(),
  is_nickname_changeable: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "max_age": "maxAge",
    "created_at": "createdAt",
    "expires_at": "expiresAt",
    "is_contact": "isContact",
    "guild_id": "guildId",
    "target_type": "targetType",
    "target_user": "targetUser",
    "target_application": "targetApplication",
    "guild_scheduled_event": "guildScheduledEvent",
    "max_uses": "maxUses",
    "approximate_member_count": "approximateMemberCount",
    "approximate_presence_count": "approximatePresenceCount",
    "is_nickname_changeable": "isNicknameChangeable",
  });
});

/** @internal */
export type GuildInviteResponse$Outbound = {
  type: 0;
  code: string;
  inviter?: UserResponse$Outbound | undefined;
  max_age?: number | undefined;
  created_at?: string | undefined;
  expires_at?: string | null | undefined;
  is_contact?: boolean | undefined;
  flags?: number | undefined;
  guild: InviteGuildResponse$Outbound;
  guild_id: string;
  channel: InviteChannelResponse$Outbound;
  target_type: 1;
  target_user?: UserResponse$Outbound | undefined;
  target_application?: InviteApplicationResponse$Outbound | undefined;
  guild_scheduled_event?: ScheduledEventResponse$Outbound | undefined;
  uses?: number | undefined;
  max_uses?: number | undefined;
  temporary?: boolean | undefined;
  approximate_member_count?: number | null | undefined;
  approximate_presence_count?: number | null | undefined;
  is_nickname_changeable?: boolean | undefined;
};

/** @internal */
export const GuildInviteResponse$outboundSchema: z.ZodType<
  GuildInviteResponse$Outbound,
  z.ZodTypeDef,
  GuildInviteResponse
> = z.object({
  type: z.literal(0).default(0 as const),
  code: z.string(),
  inviter: UserResponse$outboundSchema.optional(),
  maxAge: z.number().int().optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  expiresAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  isContact: z.boolean().optional(),
  flags: z.number().int().optional(),
  guild: InviteGuildResponse$outboundSchema,
  guildId: z.string(),
  channel: InviteChannelResponse$outboundSchema,
  targetType: z.literal(1).default(1 as const),
  targetUser: UserResponse$outboundSchema.optional(),
  targetApplication: InviteApplicationResponse$outboundSchema.optional(),
  guildScheduledEvent: ScheduledEventResponse$outboundSchema.optional(),
  uses: z.number().int().optional(),
  maxUses: z.number().int().optional(),
  temporary: z.boolean().optional(),
  approximateMemberCount: z.nullable(z.number().int()).optional(),
  approximatePresenceCount: z.nullable(z.number().int()).optional(),
  isNicknameChangeable: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    maxAge: "max_age",
    createdAt: "created_at",
    expiresAt: "expires_at",
    isContact: "is_contact",
    guildId: "guild_id",
    targetType: "target_type",
    targetUser: "target_user",
    targetApplication: "target_application",
    guildScheduledEvent: "guild_scheduled_event",
    maxUses: "max_uses",
    approximateMemberCount: "approximate_member_count",
    approximatePresenceCount: "approximate_presence_count",
    isNicknameChangeable: "is_nickname_changeable",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GuildInviteResponse$ {
  /** @deprecated use `GuildInviteResponse$inboundSchema` instead. */
  export const inboundSchema = GuildInviteResponse$inboundSchema;
  /** @deprecated use `GuildInviteResponse$outboundSchema` instead. */
  export const outboundSchema = GuildInviteResponse$outboundSchema;
  /** @deprecated use `GuildInviteResponse$Outbound` instead. */
  export type Outbound = GuildInviteResponse$Outbound;
}

export function guildInviteResponseToJSON(
  guildInviteResponse: GuildInviteResponse,
): string {
  return JSON.stringify(
    GuildInviteResponse$outboundSchema.parse(guildInviteResponse),
  );
}

export function guildInviteResponseFromJSON(
  jsonString: string,
): SafeParseResult<GuildInviteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GuildInviteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GuildInviteResponse' from JSON`,
  );
}
