/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ApplicationCommandOptionNumberChoice,
  ApplicationCommandOptionNumberChoice$inboundSchema,
  ApplicationCommandOptionNumberChoice$Outbound,
  ApplicationCommandOptionNumberChoice$outboundSchema,
} from "./applicationcommandoptionnumberchoice.js";

export type InteractionApplicationCommandAutocompleteCallbackNumberData = {
  choices?:
    | Array<ApplicationCommandOptionNumberChoice | null>
    | null
    | undefined;
};

/** @internal */
export const InteractionApplicationCommandAutocompleteCallbackNumberData$inboundSchema:
  z.ZodType<
    InteractionApplicationCommandAutocompleteCallbackNumberData,
    z.ZodTypeDef,
    unknown
  > = z.object({
    choices: z.nullable(
      z.array(z.nullable(ApplicationCommandOptionNumberChoice$inboundSchema)),
    ).optional(),
  });
/** @internal */
export type InteractionApplicationCommandAutocompleteCallbackNumberData$Outbound =
  {
    choices?:
      | Array<ApplicationCommandOptionNumberChoice$Outbound | null>
      | null
      | undefined;
  };

/** @internal */
export const InteractionApplicationCommandAutocompleteCallbackNumberData$outboundSchema:
  z.ZodType<
    InteractionApplicationCommandAutocompleteCallbackNumberData$Outbound,
    z.ZodTypeDef,
    InteractionApplicationCommandAutocompleteCallbackNumberData
  > = z.object({
    choices: z.nullable(
      z.array(z.nullable(ApplicationCommandOptionNumberChoice$outboundSchema)),
    ).optional(),
  });

export function interactionApplicationCommandAutocompleteCallbackNumberDataToJSON(
  interactionApplicationCommandAutocompleteCallbackNumberData:
    InteractionApplicationCommandAutocompleteCallbackNumberData,
): string {
  return JSON.stringify(
    InteractionApplicationCommandAutocompleteCallbackNumberData$outboundSchema
      .parse(interactionApplicationCommandAutocompleteCallbackNumberData),
  );
}
export function interactionApplicationCommandAutocompleteCallbackNumberDataFromJSON(
  jsonString: string,
): SafeParseResult<
  InteractionApplicationCommandAutocompleteCallbackNumberData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      InteractionApplicationCommandAutocompleteCallbackNumberData$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'InteractionApplicationCommandAutocompleteCallbackNumberData' from JSON`,
  );
}
