/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MentionSpamTriggerMetadata = {
  mentionTotalLimit?: number | null | undefined;
  mentionRaidProtectionEnabled?: boolean | null | undefined;
};

/** @internal */
export const MentionSpamTriggerMetadata$inboundSchema: z.ZodType<
  MentionSpamTriggerMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  mention_total_limit: z.nullable(z.number().int()).optional(),
  mention_raid_protection_enabled: z.nullable(z.boolean()).optional(),
}).transform((v) => {
  return remap$(v, {
    "mention_total_limit": "mentionTotalLimit",
    "mention_raid_protection_enabled": "mentionRaidProtectionEnabled",
  });
});
/** @internal */
export type MentionSpamTriggerMetadata$Outbound = {
  mention_total_limit?: number | null | undefined;
  mention_raid_protection_enabled?: boolean | null | undefined;
};

/** @internal */
export const MentionSpamTriggerMetadata$outboundSchema: z.ZodType<
  MentionSpamTriggerMetadata$Outbound,
  z.ZodTypeDef,
  MentionSpamTriggerMetadata
> = z.object({
  mentionTotalLimit: z.nullable(z.number().int()).optional(),
  mentionRaidProtectionEnabled: z.nullable(z.boolean()).optional(),
}).transform((v) => {
  return remap$(v, {
    mentionTotalLimit: "mention_total_limit",
    mentionRaidProtectionEnabled: "mention_raid_protection_enabled",
  });
});

export function mentionSpamTriggerMetadataToJSON(
  mentionSpamTriggerMetadata: MentionSpamTriggerMetadata,
): string {
  return JSON.stringify(
    MentionSpamTriggerMetadata$outboundSchema.parse(mentionSpamTriggerMetadata),
  );
}
export function mentionSpamTriggerMetadataFromJSON(
  jsonString: string,
): SafeParseResult<MentionSpamTriggerMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MentionSpamTriggerMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MentionSpamTriggerMetadata' from JSON`,
  );
}
