/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RoleSelectDefaultValue,
  RoleSelectDefaultValue$inboundSchema,
  RoleSelectDefaultValue$Outbound,
  RoleSelectDefaultValue$outboundSchema,
} from "./roleselectdefaultvalue.js";
import {
  UserSelectDefaultValue,
  UserSelectDefaultValue$inboundSchema,
  UserSelectDefaultValue$Outbound,
  UserSelectDefaultValue$outboundSchema,
} from "./userselectdefaultvalue.js";

/**
 * Container for other components
 */
export const MentionableSelectComponentForModalRequestType = {
  One: 1,
  Two: 2,
  Three: 3,
  Four: 4,
  Five: 5,
  Six: 6,
  Seven: 7,
  Eight: 8,
  Nine: 9,
  Ten: 10,
  Eleven: 11,
  Twelve: 12,
  Thirteen: 13,
  Fourteen: 14,
  Seventeen: 17,
  Eighteen: 18,
  Nineteen: 19,
  TwentyOne: 21,
  TwentyTwo: 22,
  TwentyThree: 23,
} as const;
/**
 * Container for other components
 */
export type MentionableSelectComponentForModalRequestType = ClosedEnum<
  typeof MentionableSelectComponentForModalRequestType
>;

export type MentionableSelectComponentForModalRequestDefaultValues =
  | RoleSelectDefaultValue
  | UserSelectDefaultValue;

export type MentionableSelectComponentForModalRequest = {
  type: MentionableSelectComponentForModalRequestType;
  id?: number | null | undefined;
  customId: string;
  placeholder?: string | null | undefined;
  minValues?: number | null | undefined;
  maxValues?: number | null | undefined;
  disabled?: boolean | null | undefined;
  required?: boolean | null | undefined;
  defaultValues?:
    | Array<RoleSelectDefaultValue | UserSelectDefaultValue>
    | null
    | undefined;
};

/** @internal */
export const MentionableSelectComponentForModalRequestType$inboundSchema:
  z.ZodNativeEnum<typeof MentionableSelectComponentForModalRequestType> = z
    .nativeEnum(MentionableSelectComponentForModalRequestType);
/** @internal */
export const MentionableSelectComponentForModalRequestType$outboundSchema:
  z.ZodNativeEnum<typeof MentionableSelectComponentForModalRequestType> =
    MentionableSelectComponentForModalRequestType$inboundSchema;

/** @internal */
export const MentionableSelectComponentForModalRequestDefaultValues$inboundSchema:
  z.ZodType<
    MentionableSelectComponentForModalRequestDefaultValues,
    z.ZodTypeDef,
    unknown
  > = z.union([
    RoleSelectDefaultValue$inboundSchema,
    UserSelectDefaultValue$inboundSchema,
  ]);
/** @internal */
export type MentionableSelectComponentForModalRequestDefaultValues$Outbound =
  | RoleSelectDefaultValue$Outbound
  | UserSelectDefaultValue$Outbound;

/** @internal */
export const MentionableSelectComponentForModalRequestDefaultValues$outboundSchema:
  z.ZodType<
    MentionableSelectComponentForModalRequestDefaultValues$Outbound,
    z.ZodTypeDef,
    MentionableSelectComponentForModalRequestDefaultValues
  > = z.union([
    RoleSelectDefaultValue$outboundSchema,
    UserSelectDefaultValue$outboundSchema,
  ]);

export function mentionableSelectComponentForModalRequestDefaultValuesToJSON(
  mentionableSelectComponentForModalRequestDefaultValues:
    MentionableSelectComponentForModalRequestDefaultValues,
): string {
  return JSON.stringify(
    MentionableSelectComponentForModalRequestDefaultValues$outboundSchema.parse(
      mentionableSelectComponentForModalRequestDefaultValues,
    ),
  );
}
export function mentionableSelectComponentForModalRequestDefaultValuesFromJSON(
  jsonString: string,
): SafeParseResult<
  MentionableSelectComponentForModalRequestDefaultValues,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MentionableSelectComponentForModalRequestDefaultValues$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'MentionableSelectComponentForModalRequestDefaultValues' from JSON`,
  );
}

/** @internal */
export const MentionableSelectComponentForModalRequest$inboundSchema: z.ZodType<
  MentionableSelectComponentForModalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: MentionableSelectComponentForModalRequestType$inboundSchema,
  id: z.nullable(z.number().int()).optional(),
  custom_id: z.string(),
  placeholder: z.nullable(z.string()).optional(),
  min_values: z.nullable(z.number().int()).optional(),
  max_values: z.nullable(z.number().int()).optional(),
  disabled: z.nullable(z.boolean()).optional(),
  required: z.nullable(z.boolean()).optional(),
  default_values: z.nullable(
    z.array(
      z.union([
        RoleSelectDefaultValue$inboundSchema,
        UserSelectDefaultValue$inboundSchema,
      ]),
    ),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "custom_id": "customId",
    "min_values": "minValues",
    "max_values": "maxValues",
    "default_values": "defaultValues",
  });
});
/** @internal */
export type MentionableSelectComponentForModalRequest$Outbound = {
  type: number;
  id?: number | null | undefined;
  custom_id: string;
  placeholder?: string | null | undefined;
  min_values?: number | null | undefined;
  max_values?: number | null | undefined;
  disabled?: boolean | null | undefined;
  required?: boolean | null | undefined;
  default_values?:
    | Array<RoleSelectDefaultValue$Outbound | UserSelectDefaultValue$Outbound>
    | null
    | undefined;
};

/** @internal */
export const MentionableSelectComponentForModalRequest$outboundSchema:
  z.ZodType<
    MentionableSelectComponentForModalRequest$Outbound,
    z.ZodTypeDef,
    MentionableSelectComponentForModalRequest
  > = z.object({
    type: MentionableSelectComponentForModalRequestType$outboundSchema,
    id: z.nullable(z.number().int()).optional(),
    customId: z.string(),
    placeholder: z.nullable(z.string()).optional(),
    minValues: z.nullable(z.number().int()).optional(),
    maxValues: z.nullable(z.number().int()).optional(),
    disabled: z.nullable(z.boolean()).optional(),
    required: z.nullable(z.boolean()).optional(),
    defaultValues: z.nullable(
      z.array(
        z.union([
          RoleSelectDefaultValue$outboundSchema,
          UserSelectDefaultValue$outboundSchema,
        ]),
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      customId: "custom_id",
      minValues: "min_values",
      maxValues: "max_values",
      defaultValues: "default_values",
    });
  });

export function mentionableSelectComponentForModalRequestToJSON(
  mentionableSelectComponentForModalRequest:
    MentionableSelectComponentForModalRequest,
): string {
  return JSON.stringify(
    MentionableSelectComponentForModalRequest$outboundSchema.parse(
      mentionableSelectComponentForModalRequest,
    ),
  );
}
export function mentionableSelectComponentForModalRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  MentionableSelectComponentForModalRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MentionableSelectComponentForModalRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'MentionableSelectComponentForModalRequest' from JSON`,
  );
}
