/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RoleSelectDefaultValueResponse,
  RoleSelectDefaultValueResponse$inboundSchema,
  RoleSelectDefaultValueResponse$Outbound,
  RoleSelectDefaultValueResponse$outboundSchema,
} from "./roleselectdefaultvalueresponse.js";
import {
  UserSelectDefaultValueResponse,
  UserSelectDefaultValueResponse$inboundSchema,
  UserSelectDefaultValueResponse$Outbound,
  UserSelectDefaultValueResponse$outboundSchema,
} from "./userselectdefaultvalueresponse.js";

/**
 * Container for other components
 */
export const MentionableSelectComponentResponseType = {
  One: 1,
  Two: 2,
  Three: 3,
  Four: 4,
  Five: 5,
  Six: 6,
  Seven: 7,
  Eight: 8,
  Nine: 9,
  Ten: 10,
  Eleven: 11,
  Twelve: 12,
  Thirteen: 13,
  Fourteen: 14,
  Seventeen: 17,
  Eighteen: 18,
  Nineteen: 19,
  TwentyOne: 21,
  TwentyTwo: 22,
  TwentyThree: 23,
} as const;
/**
 * Container for other components
 */
export type MentionableSelectComponentResponseType = ClosedEnum<
  typeof MentionableSelectComponentResponseType
>;

export type DefaultValues =
  | RoleSelectDefaultValueResponse
  | UserSelectDefaultValueResponse;

export type MentionableSelectComponentResponse = {
  type: MentionableSelectComponentResponseType;
  id: number;
  customId: string;
  placeholder?: string | undefined;
  minValues: number;
  maxValues: number;
  disabled?: boolean | undefined;
  defaultValues?:
    | Array<RoleSelectDefaultValueResponse | UserSelectDefaultValueResponse>
    | undefined;
};

/** @internal */
export const MentionableSelectComponentResponseType$inboundSchema:
  z.ZodNativeEnum<typeof MentionableSelectComponentResponseType> = z.nativeEnum(
    MentionableSelectComponentResponseType,
  );
/** @internal */
export const MentionableSelectComponentResponseType$outboundSchema:
  z.ZodNativeEnum<typeof MentionableSelectComponentResponseType> =
    MentionableSelectComponentResponseType$inboundSchema;

/** @internal */
export const DefaultValues$inboundSchema: z.ZodType<
  DefaultValues,
  z.ZodTypeDef,
  unknown
> = z.union([
  RoleSelectDefaultValueResponse$inboundSchema,
  UserSelectDefaultValueResponse$inboundSchema,
]);
/** @internal */
export type DefaultValues$Outbound =
  | RoleSelectDefaultValueResponse$Outbound
  | UserSelectDefaultValueResponse$Outbound;

/** @internal */
export const DefaultValues$outboundSchema: z.ZodType<
  DefaultValues$Outbound,
  z.ZodTypeDef,
  DefaultValues
> = z.union([
  RoleSelectDefaultValueResponse$outboundSchema,
  UserSelectDefaultValueResponse$outboundSchema,
]);

export function defaultValuesToJSON(defaultValues: DefaultValues): string {
  return JSON.stringify(DefaultValues$outboundSchema.parse(defaultValues));
}
export function defaultValuesFromJSON(
  jsonString: string,
): SafeParseResult<DefaultValues, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DefaultValues$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DefaultValues' from JSON`,
  );
}

/** @internal */
export const MentionableSelectComponentResponse$inboundSchema: z.ZodType<
  MentionableSelectComponentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: MentionableSelectComponentResponseType$inboundSchema,
  id: z.number().int(),
  custom_id: z.string(),
  placeholder: z.string().optional(),
  min_values: z.number().int(),
  max_values: z.number().int(),
  disabled: z.boolean().optional(),
  default_values: z.array(
    z.union([
      RoleSelectDefaultValueResponse$inboundSchema,
      UserSelectDefaultValueResponse$inboundSchema,
    ]),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "custom_id": "customId",
    "min_values": "minValues",
    "max_values": "maxValues",
    "default_values": "defaultValues",
  });
});
/** @internal */
export type MentionableSelectComponentResponse$Outbound = {
  type: number;
  id: number;
  custom_id: string;
  placeholder?: string | undefined;
  min_values: number;
  max_values: number;
  disabled?: boolean | undefined;
  default_values?:
    | Array<
      | RoleSelectDefaultValueResponse$Outbound
      | UserSelectDefaultValueResponse$Outbound
    >
    | undefined;
};

/** @internal */
export const MentionableSelectComponentResponse$outboundSchema: z.ZodType<
  MentionableSelectComponentResponse$Outbound,
  z.ZodTypeDef,
  MentionableSelectComponentResponse
> = z.object({
  type: MentionableSelectComponentResponseType$outboundSchema,
  id: z.number().int(),
  customId: z.string(),
  placeholder: z.string().optional(),
  minValues: z.number().int(),
  maxValues: z.number().int(),
  disabled: z.boolean().optional(),
  defaultValues: z.array(
    z.union([
      RoleSelectDefaultValueResponse$outboundSchema,
      UserSelectDefaultValueResponse$outboundSchema,
    ]),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    customId: "custom_id",
    minValues: "min_values",
    maxValues: "max_values",
    defaultValues: "default_values",
  });
});

export function mentionableSelectComponentResponseToJSON(
  mentionableSelectComponentResponse: MentionableSelectComponentResponse,
): string {
  return JSON.stringify(
    MentionableSelectComponentResponse$outboundSchema.parse(
      mentionableSelectComponentResponse,
    ),
  );
}
export function mentionableSelectComponentResponseFromJSON(
  jsonString: string,
): SafeParseResult<MentionableSelectComponentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MentionableSelectComponentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MentionableSelectComponentResponse' from JSON`,
  );
}
