/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MessageEmbedVideoResponse = {
  url?: string | undefined;
  proxyUrl?: string | undefined;
  width?: number | undefined;
  height?: number | undefined;
  contentType?: string | undefined;
  placeholder?: string | undefined;
  placeholderVersion?: number | undefined;
  description?: string | undefined;
  flags?: number | undefined;
};

/** @internal */
export const MessageEmbedVideoResponse$inboundSchema: z.ZodType<
  MessageEmbedVideoResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string().optional(),
  proxy_url: z.string().optional(),
  width: z.number().int().optional(),
  height: z.number().int().optional(),
  content_type: z.string().optional(),
  placeholder: z.string().optional(),
  placeholder_version: z.number().int().optional(),
  description: z.string().optional(),
  flags: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "proxy_url": "proxyUrl",
    "content_type": "contentType",
    "placeholder_version": "placeholderVersion",
  });
});
/** @internal */
export type MessageEmbedVideoResponse$Outbound = {
  url?: string | undefined;
  proxy_url?: string | undefined;
  width?: number | undefined;
  height?: number | undefined;
  content_type?: string | undefined;
  placeholder?: string | undefined;
  placeholder_version?: number | undefined;
  description?: string | undefined;
  flags?: number | undefined;
};

/** @internal */
export const MessageEmbedVideoResponse$outboundSchema: z.ZodType<
  MessageEmbedVideoResponse$Outbound,
  z.ZodTypeDef,
  MessageEmbedVideoResponse
> = z.object({
  url: z.string().optional(),
  proxyUrl: z.string().optional(),
  width: z.number().int().optional(),
  height: z.number().int().optional(),
  contentType: z.string().optional(),
  placeholder: z.string().optional(),
  placeholderVersion: z.number().int().optional(),
  description: z.string().optional(),
  flags: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    proxyUrl: "proxy_url",
    contentType: "content_type",
    placeholderVersion: "placeholder_version",
  });
});

export function messageEmbedVideoResponseToJSON(
  messageEmbedVideoResponse: MessageEmbedVideoResponse,
): string {
  return JSON.stringify(
    MessageEmbedVideoResponse$outboundSchema.parse(messageEmbedVideoResponse),
  );
}
export function messageEmbedVideoResponseFromJSON(
  jsonString: string,
): SafeParseResult<MessageEmbedVideoResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageEmbedVideoResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageEmbedVideoResponse' from JSON`,
  );
}
