/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MessageEmbedAuthorResponse = {
  name: string;
  url?: string | undefined;
  iconUrl?: string | undefined;
  proxyIconUrl?: string | undefined;
};

/** @internal */
export const MessageEmbedAuthorResponse$inboundSchema: z.ZodType<
  MessageEmbedAuthorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  url: z.string().optional(),
  icon_url: z.string().optional(),
  proxy_icon_url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "icon_url": "iconUrl",
    "proxy_icon_url": "proxyIconUrl",
  });
});
/** @internal */
export type MessageEmbedAuthorResponse$Outbound = {
  name: string;
  url?: string | undefined;
  icon_url?: string | undefined;
  proxy_icon_url?: string | undefined;
};

/** @internal */
export const MessageEmbedAuthorResponse$outboundSchema: z.ZodType<
  MessageEmbedAuthorResponse$Outbound,
  z.ZodTypeDef,
  MessageEmbedAuthorResponse
> = z.object({
  name: z.string(),
  url: z.string().optional(),
  iconUrl: z.string().optional(),
  proxyIconUrl: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    iconUrl: "icon_url",
    proxyIconUrl: "proxy_icon_url",
  });
});

export function messageEmbedAuthorResponseToJSON(
  messageEmbedAuthorResponse: MessageEmbedAuthorResponse,
): string {
  return JSON.stringify(
    MessageEmbedAuthorResponse$outboundSchema.parse(messageEmbedAuthorResponse),
  );
}
export function messageEmbedAuthorResponseFromJSON(
  jsonString: string,
): SafeParseResult<MessageEmbedAuthorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageEmbedAuthorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageEmbedAuthorResponse' from JSON`,
  );
}
