/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PinnedMessageResponse,
  PinnedMessageResponse$inboundSchema,
  PinnedMessageResponse$Outbound,
  PinnedMessageResponse$outboundSchema,
} from "./pinnedmessageresponse.js";

export type PinnedMessagesResponse = {
  items: Array<PinnedMessageResponse>;
  hasMore: boolean;
};

/** @internal */
export const PinnedMessagesResponse$inboundSchema: z.ZodType<
  PinnedMessagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(PinnedMessageResponse$inboundSchema),
  has_more: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "has_more": "hasMore",
  });
});

/** @internal */
export type PinnedMessagesResponse$Outbound = {
  items: Array<PinnedMessageResponse$Outbound>;
  has_more: boolean;
};

/** @internal */
export const PinnedMessagesResponse$outboundSchema: z.ZodType<
  PinnedMessagesResponse$Outbound,
  z.ZodTypeDef,
  PinnedMessagesResponse
> = z.object({
  items: z.array(PinnedMessageResponse$outboundSchema),
  hasMore: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    hasMore: "has_more",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PinnedMessagesResponse$ {
  /** @deprecated use `PinnedMessagesResponse$inboundSchema` instead. */
  export const inboundSchema = PinnedMessagesResponse$inboundSchema;
  /** @deprecated use `PinnedMessagesResponse$outboundSchema` instead. */
  export const outboundSchema = PinnedMessagesResponse$outboundSchema;
  /** @deprecated use `PinnedMessagesResponse$Outbound` instead. */
  export type Outbound = PinnedMessagesResponse$Outbound;
}

export function pinnedMessagesResponseToJSON(
  pinnedMessagesResponse: PinnedMessagesResponse,
): string {
  return JSON.stringify(
    PinnedMessagesResponse$outboundSchema.parse(pinnedMessagesResponse),
  );
}

export function pinnedMessagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PinnedMessagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PinnedMessagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PinnedMessagesResponse' from JSON`,
  );
}
