/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PollEmojiCreateRequest,
  PollEmojiCreateRequest$inboundSchema,
  PollEmojiCreateRequest$Outbound,
  PollEmojiCreateRequest$outboundSchema,
} from "./pollemojicreaterequest.js";

export type PollMediaCreateRequest = {
  /**
   * The text of the field
   */
  text?: string | null | undefined;
  /**
   * The emoji of the field
   */
  emoji?: PollEmojiCreateRequest | null | undefined;
};

/** @internal */
export const PollMediaCreateRequest$inboundSchema: z.ZodType<
  PollMediaCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.nullable(z.string()).optional(),
  emoji: z.nullable(PollEmojiCreateRequest$inboundSchema).optional(),
});
/** @internal */
export type PollMediaCreateRequest$Outbound = {
  text?: string | null | undefined;
  emoji?: PollEmojiCreateRequest$Outbound | null | undefined;
};

/** @internal */
export const PollMediaCreateRequest$outboundSchema: z.ZodType<
  PollMediaCreateRequest$Outbound,
  z.ZodTypeDef,
  PollMediaCreateRequest
> = z.object({
  text: z.nullable(z.string()).optional(),
  emoji: z.nullable(PollEmojiCreateRequest$outboundSchema).optional(),
});

export function pollMediaCreateRequestToJSON(
  pollMediaCreateRequest: PollMediaCreateRequest,
): string {
  return JSON.stringify(
    PollMediaCreateRequest$outboundSchema.parse(pollMediaCreateRequest),
  );
}
export function pollMediaCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<PollMediaCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PollMediaCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PollMediaCreateRequest' from JSON`,
  );
}
