/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Container for other components
 */
export const TextInputComponentResponseType = {
  One: 1,
  Two: 2,
  Three: 3,
  Four: 4,
  Five: 5,
  Six: 6,
  Seven: 7,
  Eight: 8,
  Nine: 9,
  Ten: 10,
  Eleven: 11,
  Twelve: 12,
  Thirteen: 13,
  Fourteen: 14,
  Seventeen: 17,
  Eighteen: 18,
  Nineteen: 19,
  TwentyOne: 21,
  TwentyTwo: 22,
  TwentyThree: 23,
} as const;
/**
 * Container for other components
 */
export type TextInputComponentResponseType = ClosedEnum<
  typeof TextInputComponentResponseType
>;

/**
 * Single-line input
 */
export const TextInputStyleTypes = {
  One: 1,
  Two: 2,
} as const;
/**
 * Single-line input
 */
export type TextInputStyleTypes = ClosedEnum<typeof TextInputStyleTypes>;

export type TextInputComponentResponse = {
  type: TextInputComponentResponseType;
  id: number;
  customId: string;
  style: TextInputStyleTypes;
  label: string | null;
  value?: string | undefined;
  placeholder?: string | undefined;
  required?: boolean | undefined;
  minLength: number | null;
  maxLength: number | null;
};

/**
 * Container for other components
 */
export const TextInputComponentForModalRequestType = {
  One: 1,
  Two: 2,
  Three: 3,
  Four: 4,
  Five: 5,
  Six: 6,
  Seven: 7,
  Eight: 8,
  Nine: 9,
  Ten: 10,
  Eleven: 11,
  Twelve: 12,
  Thirteen: 13,
  Fourteen: 14,
  Seventeen: 17,
  Eighteen: 18,
  Nineteen: 19,
  TwentyOne: 21,
  TwentyTwo: 22,
  TwentyThree: 23,
} as const;
/**
 * Container for other components
 */
export type TextInputComponentForModalRequestType = ClosedEnum<
  typeof TextInputComponentForModalRequestType
>;

export type TextInputComponentForModalRequest = {
  type: TextInputComponentForModalRequestType;
  id?: number | null | undefined;
  customId: string;
  style: TextInputStyleTypes;
  label?: string | null | undefined;
  value?: string | null | undefined;
  placeholder?: string | null | undefined;
  required?: boolean | null | undefined;
  minLength?: number | null | undefined;
  maxLength?: number | null | undefined;
};

/** @internal */
export const TextInputComponentResponseType$inboundSchema: z.ZodNativeEnum<
  typeof TextInputComponentResponseType
> = z.nativeEnum(TextInputComponentResponseType);
/** @internal */
export const TextInputComponentResponseType$outboundSchema: z.ZodNativeEnum<
  typeof TextInputComponentResponseType
> = TextInputComponentResponseType$inboundSchema;

/** @internal */
export const TextInputStyleTypes$inboundSchema: z.ZodNativeEnum<
  typeof TextInputStyleTypes
> = z.nativeEnum(TextInputStyleTypes);
/** @internal */
export const TextInputStyleTypes$outboundSchema: z.ZodNativeEnum<
  typeof TextInputStyleTypes
> = TextInputStyleTypes$inboundSchema;

/** @internal */
export const TextInputComponentResponse$inboundSchema: z.ZodType<
  TextInputComponentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: TextInputComponentResponseType$inboundSchema,
  id: z.number().int(),
  custom_id: z.string(),
  style: TextInputStyleTypes$inboundSchema,
  label: z.nullable(z.string()),
  value: z.string().optional(),
  placeholder: z.string().optional(),
  required: z.boolean().optional(),
  min_length: z.nullable(z.number().int()),
  max_length: z.nullable(z.number().int()),
}).transform((v) => {
  return remap$(v, {
    "custom_id": "customId",
    "min_length": "minLength",
    "max_length": "maxLength",
  });
});
/** @internal */
export type TextInputComponentResponse$Outbound = {
  type: number;
  id: number;
  custom_id: string;
  style: number;
  label: string | null;
  value?: string | undefined;
  placeholder?: string | undefined;
  required?: boolean | undefined;
  min_length: number | null;
  max_length: number | null;
};

/** @internal */
export const TextInputComponentResponse$outboundSchema: z.ZodType<
  TextInputComponentResponse$Outbound,
  z.ZodTypeDef,
  TextInputComponentResponse
> = z.object({
  type: TextInputComponentResponseType$outboundSchema,
  id: z.number().int(),
  customId: z.string(),
  style: TextInputStyleTypes$outboundSchema,
  label: z.nullable(z.string()),
  value: z.string().optional(),
  placeholder: z.string().optional(),
  required: z.boolean().optional(),
  minLength: z.nullable(z.number().int()),
  maxLength: z.nullable(z.number().int()),
}).transform((v) => {
  return remap$(v, {
    customId: "custom_id",
    minLength: "min_length",
    maxLength: "max_length",
  });
});

export function textInputComponentResponseToJSON(
  textInputComponentResponse: TextInputComponentResponse,
): string {
  return JSON.stringify(
    TextInputComponentResponse$outboundSchema.parse(textInputComponentResponse),
  );
}
export function textInputComponentResponseFromJSON(
  jsonString: string,
): SafeParseResult<TextInputComponentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextInputComponentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextInputComponentResponse' from JSON`,
  );
}

/** @internal */
export const TextInputComponentForModalRequestType$inboundSchema:
  z.ZodNativeEnum<typeof TextInputComponentForModalRequestType> = z.nativeEnum(
    TextInputComponentForModalRequestType,
  );
/** @internal */
export const TextInputComponentForModalRequestType$outboundSchema:
  z.ZodNativeEnum<typeof TextInputComponentForModalRequestType> =
    TextInputComponentForModalRequestType$inboundSchema;

/** @internal */
export const TextInputComponentForModalRequest$inboundSchema: z.ZodType<
  TextInputComponentForModalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: TextInputComponentForModalRequestType$inboundSchema,
  id: z.nullable(z.number().int()).optional(),
  custom_id: z.string(),
  style: TextInputStyleTypes$inboundSchema,
  label: z.nullable(z.string()).optional(),
  value: z.nullable(z.string()).optional(),
  placeholder: z.nullable(z.string()).optional(),
  required: z.nullable(z.boolean()).optional(),
  min_length: z.nullable(z.number().int()).optional(),
  max_length: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "custom_id": "customId",
    "min_length": "minLength",
    "max_length": "maxLength",
  });
});
/** @internal */
export type TextInputComponentForModalRequest$Outbound = {
  type: number;
  id?: number | null | undefined;
  custom_id: string;
  style: number;
  label?: string | null | undefined;
  value?: string | null | undefined;
  placeholder?: string | null | undefined;
  required?: boolean | null | undefined;
  min_length?: number | null | undefined;
  max_length?: number | null | undefined;
};

/** @internal */
export const TextInputComponentForModalRequest$outboundSchema: z.ZodType<
  TextInputComponentForModalRequest$Outbound,
  z.ZodTypeDef,
  TextInputComponentForModalRequest
> = z.object({
  type: TextInputComponentForModalRequestType$outboundSchema,
  id: z.nullable(z.number().int()).optional(),
  customId: z.string(),
  style: TextInputStyleTypes$outboundSchema,
  label: z.nullable(z.string()).optional(),
  value: z.nullable(z.string()).optional(),
  placeholder: z.nullable(z.string()).optional(),
  required: z.nullable(z.boolean()).optional(),
  minLength: z.nullable(z.number().int()).optional(),
  maxLength: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    customId: "custom_id",
    minLength: "min_length",
    maxLength: "max_length",
  });
});

export function textInputComponentForModalRequestToJSON(
  textInputComponentForModalRequest: TextInputComponentForModalRequest,
): string {
  return JSON.stringify(
    TextInputComponentForModalRequest$outboundSchema.parse(
      textInputComponentForModalRequest,
    ),
  );
}
export function textInputComponentForModalRequestFromJSON(
  jsonString: string,
): SafeParseResult<TextInputComponentForModalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextInputComponentForModalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextInputComponentForModalRequest' from JSON`,
  );
}
