/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ThreadResponse,
  ThreadResponse$inboundSchema,
  ThreadResponse$Outbound,
  ThreadResponse$outboundSchema,
} from "./guildsearch.js";
import {
  MessageResponse,
  MessageResponse$inboundSchema,
  MessageResponse$Outbound,
  MessageResponse$outboundSchema,
} from "./messageresponse.js";
import {
  ThreadMemberResponse,
  ThreadMemberResponse$inboundSchema,
  ThreadMemberResponse$Outbound,
  ThreadMemberResponse$outboundSchema,
} from "./threadmemberresponse.js";

export type ThreadSearchResponse = {
  threads: Array<ThreadResponse>;
  members: Array<ThreadMemberResponse>;
  hasMore: boolean;
  firstMessages?: Array<MessageResponse> | undefined;
  totalResults: number;
};

/** @internal */
export const ThreadSearchResponse$inboundSchema: z.ZodType<
  ThreadSearchResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  threads: z.array(ThreadResponse$inboundSchema),
  members: z.array(ThreadMemberResponse$inboundSchema),
  has_more: z.boolean(),
  first_messages: z.array(MessageResponse$inboundSchema).optional(),
  total_results: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "has_more": "hasMore",
    "first_messages": "firstMessages",
    "total_results": "totalResults",
  });
});
/** @internal */
export type ThreadSearchResponse$Outbound = {
  threads: Array<ThreadResponse$Outbound>;
  members: Array<ThreadMemberResponse$Outbound>;
  has_more: boolean;
  first_messages?: Array<MessageResponse$Outbound> | undefined;
  total_results: number;
};

/** @internal */
export const ThreadSearchResponse$outboundSchema: z.ZodType<
  ThreadSearchResponse$Outbound,
  z.ZodTypeDef,
  ThreadSearchResponse
> = z.object({
  threads: z.array(ThreadResponse$outboundSchema),
  members: z.array(ThreadMemberResponse$outboundSchema),
  hasMore: z.boolean(),
  firstMessages: z.array(MessageResponse$outboundSchema).optional(),
  totalResults: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    hasMore: "has_more",
    firstMessages: "first_messages",
    totalResults: "total_results",
  });
});

export function threadSearchResponseToJSON(
  threadSearchResponse: ThreadSearchResponse,
): string {
  return JSON.stringify(
    ThreadSearchResponse$outboundSchema.parse(threadSearchResponse),
  );
}
export function threadSearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<ThreadSearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThreadSearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThreadSearchResponse' from JSON`,
  );
}
