/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TypingIndicatorResponse = {};

/** @internal */
export const TypingIndicatorResponse$inboundSchema: z.ZodType<
  TypingIndicatorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type TypingIndicatorResponse$Outbound = {};

/** @internal */
export const TypingIndicatorResponse$outboundSchema: z.ZodType<
  TypingIndicatorResponse$Outbound,
  z.ZodTypeDef,
  TypingIndicatorResponse
> = z.object({});

export function typingIndicatorResponseToJSON(
  typingIndicatorResponse: TypingIndicatorResponse,
): string {
  return JSON.stringify(
    TypingIndicatorResponse$outboundSchema.parse(typingIndicatorResponse),
  );
}
export function typingIndicatorResponseFromJSON(
  jsonString: string,
): SafeParseResult<TypingIndicatorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypingIndicatorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypingIndicatorResponse' from JSON`,
  );
}
