/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Crimson color palette
 */
export const NameplatePalette = {
  Crimson: "crimson",
  Berry: "berry",
  Sky: "sky",
  Teal: "teal",
  Forest: "forest",
  BubbleGum: "bubble_gum",
  Violet: "violet",
  Cobalt: "cobalt",
  Clover: "clover",
  Lemon: "lemon",
  White: "white",
  Black: "black",
} as const;
/**
 * Crimson color palette
 */
export type NameplatePalette = ClosedEnum<typeof NameplatePalette>;

export type UserNameplateResponse = {
  /**
   * ID of the nameplate SKU
   */
  skuId: string | null;
  /**
   * Path to the nameplate asset
   */
  asset: string;
  /**
   * The label of this nameplate. Currently unused
   */
  label: string;
  palette: NameplatePalette;
};

/** @internal */
export const NameplatePalette$inboundSchema: z.ZodNativeEnum<
  typeof NameplatePalette
> = z.nativeEnum(NameplatePalette);
/** @internal */
export const NameplatePalette$outboundSchema: z.ZodNativeEnum<
  typeof NameplatePalette
> = NameplatePalette$inboundSchema;

/** @internal */
export const UserNameplateResponse$inboundSchema: z.ZodType<
  UserNameplateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  sku_id: z.nullable(z.string()),
  asset: z.string(),
  label: z.string(),
  palette: NameplatePalette$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "sku_id": "skuId",
  });
});
/** @internal */
export type UserNameplateResponse$Outbound = {
  sku_id: string | null;
  asset: string;
  label: string;
  palette: string;
};

/** @internal */
export const UserNameplateResponse$outboundSchema: z.ZodType<
  UserNameplateResponse$Outbound,
  z.ZodTypeDef,
  UserNameplateResponse
> = z.object({
  skuId: z.nullable(z.string()),
  asset: z.string(),
  label: z.string(),
  palette: NameplatePalette$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    skuId: "sku_id",
  });
});

export function userNameplateResponseToJSON(
  userNameplateResponse: UserNameplateResponse,
): string {
  return JSON.stringify(
    UserNameplateResponse$outboundSchema.parse(userNameplateResponse),
  );
}
export function userNameplateResponseFromJSON(
  jsonString: string,
): SafeParseResult<UserNameplateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserNameplateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserNameplateResponse' from JSON`,
  );
}
