/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  UserCommunicationDisabledActionMetadata,
  UserCommunicationDisabledActionMetadata$inboundSchema,
  UserCommunicationDisabledActionMetadata$Outbound,
  UserCommunicationDisabledActionMetadata$outboundSchema,
} from "./usercommunicationdisabledactionmetadata.js";

/**
 * Block a user's message and prevent it from being posted. A custom explanation can be specified and shown to members whenever their message is blocked
 */
export const UserCommunicationDisabledActionType = {
  One: 1,
  Two: 2,
  Three: 3,
  Four: 4,
} as const;
/**
 * Block a user's message and prevent it from being posted. A custom explanation can be specified and shown to members whenever their message is blocked
 */
export type UserCommunicationDisabledActionType = ClosedEnum<
  typeof UserCommunicationDisabledActionType
>;

export type UserCommunicationDisabledAction = {
  type: UserCommunicationDisabledActionType;
  metadata: UserCommunicationDisabledActionMetadata;
};

/** @internal */
export const UserCommunicationDisabledActionType$inboundSchema: z.ZodNativeEnum<
  typeof UserCommunicationDisabledActionType
> = z.nativeEnum(UserCommunicationDisabledActionType);
/** @internal */
export const UserCommunicationDisabledActionType$outboundSchema:
  z.ZodNativeEnum<typeof UserCommunicationDisabledActionType> =
    UserCommunicationDisabledActionType$inboundSchema;

/** @internal */
export const UserCommunicationDisabledAction$inboundSchema: z.ZodType<
  UserCommunicationDisabledAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: UserCommunicationDisabledActionType$inboundSchema,
  metadata: UserCommunicationDisabledActionMetadata$inboundSchema,
});
/** @internal */
export type UserCommunicationDisabledAction$Outbound = {
  type: number;
  metadata: UserCommunicationDisabledActionMetadata$Outbound;
};

/** @internal */
export const UserCommunicationDisabledAction$outboundSchema: z.ZodType<
  UserCommunicationDisabledAction$Outbound,
  z.ZodTypeDef,
  UserCommunicationDisabledAction
> = z.object({
  type: UserCommunicationDisabledActionType$outboundSchema,
  metadata: UserCommunicationDisabledActionMetadata$outboundSchema,
});

export function userCommunicationDisabledActionToJSON(
  userCommunicationDisabledAction: UserCommunicationDisabledAction,
): string {
  return JSON.stringify(
    UserCommunicationDisabledAction$outboundSchema.parse(
      userCommunicationDisabledAction,
    ),
  );
}
export function userCommunicationDisabledActionFromJSON(
  jsonString: string,
): SafeParseResult<UserCommunicationDisabledAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserCommunicationDisabledAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserCommunicationDisabledAction' from JSON`,
  );
}
